apiVersion: v1
kind: Service
metadata:
  labels:
    apps: egat-p2p-api
  name: egat-p2p-api
spec:
  ports:
    - name: "4000"
      port: 4000
      targetPort: 30000
  selector:
    apps: egat-p2p-api