apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: druid
    meta.helm.sh/release-namespace: druid
  creationTimestamp: "2021-12-01T11:09:43Z"
  generation: 1
  labels:
    app: druid
    app.kubernetes.io/managed-by: Helm
    chart: druid-0.2.18
    component: broker
    heritage: Helm
    release: druid
  name: druid-broker
  namespace: druid
  resourceVersion: "48360299"
  uid: 9a344495-a01d-4569-8e4c-d1b91805a143
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: druid
      component: broker
      release: druid
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: druid
        component: broker
        release: druid
    spec:
      nodeSelector:
        tier: ceph
      containers:
      - args:
        - broker
        env:
        - name: DRUID_MAXDIRECTMEMORYSIZE
          value: 400m
        - name: DRUID_XMS
          value: 512m
        - name: DRUID_XMX
          value: 512m
        - name: druid_processing_buffer_sizeBytes
          value: "50000000"
        - name: druid_processing_numMergeBuffers
          value: "2"
        - name: druid_processing_numThreads
          value: "1"
        envFrom:
        - configMapRef:
            name: druid
        image: apache/druid:0.19.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /status/health
            port: 8082
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: druid
        ports:
        - containerPort: 8082
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /status/health
            port: 8082
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-12-01T11:09:43Z"
    lastUpdateTime: "2021-12-01T11:22:08Z"
    message: ReplicaSet "druid-broker-7759755b49" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-01-21T02:29:51Z"
    lastUpdateTime: "2022-01-21T02:29:51Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
