apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: egat-p2p-webadmin-claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: rook-cephfs
status: {}
