apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    apps: egat-p2p-mobile-power-api
  name: egat-p2p-mobile-power-api
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: egat-p2p-mobile-power-api
  strategy: {}
  template:
    metadata:
      labels:
        apps: egat-p2p-mobile-power-api
    spec:
      containers:
        - env:
            - name: MONGO_DATABASE
              value: EnergyActualDatabase
            - name: MONGO_HOST
              value: energyactual-mongodb-0-external
            - name: MONGO_PASSWORD
              value: Passw0rdEGAT
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USER
              value: user
            - name: NODE_ENV
              value: development
          image: lenkunz/egat-p2p-power:1.0.0-beta-1
          name: egat-p2p-mobile-power-api
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
