apiVersion: v1
kind: Service
metadata:
  labels:
    apps: egat-p2p-mobile-power-api
  name: egat-p2p-mobile-power-api
spec:
  ports:
    - name: "39082"
      port: 39082
      targetPort: 3000
  selector:
    apps: egat-p2p-mobile-power-api
status:
  loadBalancer: {}
