apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --chart -f docker-compose.power.yaml
    kompose.version: 1.25.0 (a70f80cc)
  creationTimestamp: null
  labels:
    apps: app
  name: app
spec:
  ports:
    - name: "39082"
      port: 39082
      targetPort: 3000
  selector:
    apps: app
status:
  loadBalancer: {}
