apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --chart -f docker-compose.power.yaml
    kompose.version: 1.25.0 (a70f80cc)
  creationTimestamp: null
  labels:
    apps: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --chart -f docker-compose.power.yaml
        kompose.version: 1.25.0 (a70f80cc)
      creationTimestamp: null
      labels:
        apps: app
    spec:
      containers:
        - env:
            - name: MONGO_DATABASE
              value: admin
            - name: MONGO_HOST
              value: mongo
            - name: MONGO_PASSWORD
              value: example
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USER
              value: root
            - name: NODE_ENV
              value: development
          image: lenkunz/egat-p2p-power:1.0.0-beta
          name: app
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
