apiVersion: v1
kind: Service
metadata:
  name: druid-router-external-svc
  namespace: erc-p2p
spec:
  externalName: druid-router.druid.svc.cluster.local
  internalTrafficPolicy: Cluster
  sessionAffinity: None
  type: ExternalName