apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: druid
    meta.helm.sh/release-namespace: druid
  creationTimestamp: "2021-12-01T11:09:43Z"
  generation: 1
  labels:
    app: druid
    app.kubernetes.io/managed-by: Helm
    chart: druid-0.2.18
    component: coordinator
    heritage: Helm
    release: druid
  name: druid-coordinator
  namespace: druid
  resourceVersion: "48086569"
  uid: 7f11a205-9a4d-46c4-a47e-96852c8d2451
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: druid
      component: coordinator
      release: druid
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: druid
        component: coordinator
        release: druid
    spec:
      containers:
      - args:
        - coordinator
        env:
        - name: DRUID_XMS
          value: 256m
        - name: DRUID_XMX
          value: 256m
        envFrom:
        - configMapRef:
            name: druid
        image: apache/druid:0.19.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /status/health
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: druid
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /status/health
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2021-12-01T11:09:43Z"
    lastUpdateTime: "2021-12-01T11:22:08Z"
    message: ReplicaSet "druid-coordinator-79ffc694c7" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-01-20T08:31:46Z"
    lastUpdateTime: "2022-01-20T08:31:46Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
