apiVersion: v1
data:
  DRUID_USE_CONTAINER_IP: "true"
  druid_emitter: noop
  druid_emitter_http_recipientBaseUrl: http://druid_exporter_url:druid_exporter_port/druid
  druid_emitter_logging_logLevel: debug
  druid_extensions_loadList: '["druid-histogram", "druid-datasketches", "druid-lookups-cached-global",
    "postgresql-metadata-storage","druid-kafka-indexing-service"]'
  druid_indexer_logs_directory: /opt/data/indexing-logs
  druid_indexer_logs_type: file
  druid_metadata_storage_connector_connectURI: jdbc:postgresql://druid-postgresql:5432/druid
  druid_metadata_storage_connector_password: druid
  druid_metadata_storage_connector_user: druid
  druid_metadata_storage_type: postgresql
  druid_storage_type: local
  druid_worker_capacity: "16"
  druid_zk_service_host: druid-zookeeper-headless:2181
  druid_processing_numThreads: "16"
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: druid
    meta.helm.sh/release-namespace: druid
  labels:
    app: druid
    app.kubernetes.io/managed-by: Helm
    chart: druid-0.2.18
    heritage: Helm
    release: druid
  name: druid
  namespace: druid