apiVersion: v1
kind: Service
metadata:
  name: kafka-3-svc
  namespace: druid
spec:
  externalName: kafka-3-svc.kafka-connect.svc.cluster.local
  internalTrafficPolicy: Cluster
  sessionAffinity: None
  type: ExternalName
