apiVersion: v1
kind: Service
metadata:
  name: kafka-1-svc
  namespace: druid
spec:
  externalName: kafka-1-svc.kafka-connect.svc.cluster.local
  internalTrafficPolicy: Cluster
  sessionAffinity: None
  type: ExternalName
