apiVersion: v1
kind: Service
metadata:
  name: kafka-external-svc
  namespace: druid
spec:
  externalName: kafka.kafka-connect.svc.cluster.local
  internalTrafficPolicy: Cluster
  sessionAffinity: None
  type: ExternalName