apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: druid
    release: druid
  name: data
  namespace: druid
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
