apiVersion: v1
kind: Service
metadata:
  labels:
    apps: egat-p2p-register-api
  name: egat-p2p-register-api
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
      nodePort: 30001
  type: NodePort
  selector:
    apps: egat-p2p-register-api
