apiVersion: v1
kind: Service
metadata:
  name: egat-p2p-mobile-trade-hyperledger-api-external-svc
  namespace: erc-p2p
spec:
  externalName: egat-p2p-mobile-trade-hyperledger-api.hyperledger.svc.cluster.local
  internalTrafficPolicy: Cluster
  sessionAffinity: None
  type: ExternalName