apiVersion: v1
kind: Service
metadata:
  labels:
    app: egat-p2p-mobile-bilateral-hyperledger-api
  name: egat-p2p-mobile-bilateral-hyperledger-api
spec:
  ports:
    - name: "5006"
      port: 5006
      targetPort: 5006
  selector:
    app: egat-p2p-mobile-bilateral-hyperledger-api