apiVersion: v1
kind: Service
metadata:
  labels:
    apps: egat-p2p-otp-gateway-api
  name: egat-p2p-otp-gateway-api
spec:
  ports:
    - name: "4001"
      port: 4001
      targetPort: 4001
  selector:
    apps: egat-p2p-otp-gateway-api

