apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    apps: meterdb-claim0
  name: meterdb-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: rook-cephfs