apiVersion: v1
kind: Service
metadata:
  labels:
    apps: egat-p2p-mobile-power-job-api
  name: egat-p2p-mobile-power-job-api
spec:
  ports:
    - name: "39080"
      port: 39080
      targetPort: 3000
  selector:
    apps: egat-p2p-mobile-power-job-api
status:
  loadBalancer: {}
