apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    apps: egat-p2p-mobile-power-job-api
  name: egat-p2p-mobile-power-job-api
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: egat-p2p-mobile-power-job-api
  strategy: {}
  template:
    metadata:
      labels:
        apps: egat-p2p-mobile-power-job-api
    spec:
      containers:
        - env:
            - name: API_FORECAST_ENDPOINT
              value: http://egat-p2p-mobile-forecast-api:39081
            - name: API_POWER_ENDPOINT
              value: http://egat-p2p-mobile-power-api:39082
            - name: MONGO_DATABASE
              value: JobDatabase
            - name: MONGO_HOST
              value: job-mongodb-0-external
            - name: MONGO_PASSWORD
              value: Passw0rdEGAT
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USER
              value: user
            - name: NODE_ENV
              value: development
            - name: POINTNAME_ENPOINT_BASE
              value: http://10.40.62.181:20001/db
            - name: POINTNAME_TIME_UTC_OFFSET_MINUTE
              value: "420"
            - name: SRISANGTHAM_ENPOINT_BASE
              value: https://smarthomedev.egat.co.th
            - name: SRISANGTHAM_EP_ENPOINT_BASE
              value: https://ems.energy-pool.eu
            - name: SRISANGTHAM_EP_PASSWORD
              value: S3NraMv7sE#
            - name: SRISANGTHAM_EP_USERNAME
              value: a.limsupanark@egat
            - name: SRISANGTHAM_TIME_UTC_OFFSET_MINUTE
              value: "420"
          image: lenkunz/egat-p2p-power-job:1.0.0-beta
          name: egat-p2p-mobile-power-job-api
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
