apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: egat-p2p-mobile-pool-hyperledger-api
  name: egat-p2p-mobile-pool-hyperledger-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: egat-p2p-mobile-pool-hyperledger-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: egat-p2p-mobile-pool-hyperledger-api
    spec:
      containers:
        - env:
            - name: APP_AFFILIATION
              value: org1.department1
            - name: APP_CCPPATH
              value: /shared/blockchain/local-ccp.yaml
            - name: APP_CHAINCODE_CHANNEL
              value: mychannel
            - name: APP_CHAINCODE_NAME
              value: pool-log
            - name: APP_GENERIC_IDENTITY_ID
              value: generic10
            - name: APP_GENERIC_IDENTITY_MSPID
              value: org1MSP
            - name: APP_GENERIC_IDENTITY_SECRET
              value: generic10
            - name: HOST
              value: 0.0.0.0
            - name: PORT
              value: "5007"
          image: phwuts/egat-p2p-mobile-pool-hyperledger-api:0.0.1
          name: egat-p2p-mobile-pool-hyperledger-api
          ports:
            - containerPort: 5007
          resources: {}
          volumeMounts:
            - mountPath: /shared/
              name: egat-p2p-mobile-pool-hyperledger-api-claim0
            - mountPath: /home/node/store
              name: keystore
      restartPolicy: Always
      volumes:
        - name: egat-p2p-mobile-pool-hyperledger-api-claim0
          persistentVolumeClaim:
            claimName: share-pvc
        - name: egat-p2p-mobile-pool-hyperledger-api-keystore
          persistentVolumeClaim:
            claimName: egat-p2p-mobile-pool-hyperledger-api-keystore
status: {}
