apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    apps: userdb-claim0
  name: userdb-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs

