apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    apps: userdb
  name: userdb
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: userdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        apps: userdb
    spec:
      containers:
        - image: mongo:latest
          name: userdb
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: userdb-claim0
      restartPolicy: Always
      volumes:
        - name: userdb-claim0
          persistentVolumeClaim:
            claimName: userdb-claim0