apiVersion: v1
kind: Service
metadata:
  labels:
    apps: egat-p2p-web-admin-user-management-api
  name: egat-p2p-web-admin-user-management-api
spec:
  ports:
    - name: "3004"
      port: 3004
      targetPort: 3004
  selector:
    apps: egat-p2p-web-admin-user-management-api

