apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    apps: egat-p2p-mobile-forecast-api
  name: egat-p2p-mobile-forecast-api
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: egat-p2p-mobile-forecast-api
  strategy: {}
  template:
    metadata:
      labels:
        apps: egat-p2p-mobile-forecast-api
    spec:
      nodeSelector:
        tier: api
      containers:
        - env:
            - name: MONGO_DATABASE
              value: EnergyForecastDatabase
            - name: MONGO_HOST
              value: energyforecast-mongodb-0-external
            - name: MONGO_PASSWORD
              value: Passw0rdEGAT
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USER
              value: user
            - name: NODE_ENV
              value: development
          image: lenkunz/egat-p2p-forecast:1.8.0-beta
          name: egat-p2p-mobile-forecast-api
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
            limits: 
              memory: "192Mi"
      restartPolicy: Always
status: {}
