apiVersion: v1
kind: Service
metadata:
  labels:
    apps: egat-p2p-mobile-forecast-api
  name: egat-p2p-mobile-forecast-api
spec:
  ports:
    - name: "39081"
      port: 39081
      targetPort: 3000
  selector:
    apps: egat-p2p-mobile-forecast-api
status:
  loadBalancer: {}
