apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    apps: egat-p2p-meter-api
  name: egat-p2p-meter-api
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: egat-p2p-meter-api
  strategy: {}
  template:
    metadata:
      labels:
        apps: egat-p2p-meter-api
    spec:
      nodeSelector:
        tier: api
      containers:
        - env:
            - name: APP_API_KEY
              value: AIzaSyCqNmC7Pgce5a44iW8cW9HDXIFPxJDhPgQ
            - name: APP_GEOCODING_URL
              value: https://maps.googleapis.com/maps/api/geocode
            - name: HOST
              value: 0.0.0.0
            - name: MONGO_INITDB_DATABASENAME
              value: MasterDataDatabase
            - name: MONGO_INITDB_HOST
              value: masterdata-mongodb-0-external
            - name: MONGO_INITDB_PASSWORD
              value: Passw0rdEGAT
            - name: MONGO_INITDB_PORT
              value: "27017"
            - name: MONGO_INITDB_USERNAME
              value: user
            - name: PORT
              value: "4000"
            - name: NO_PROXY
              value: "127.0.0.1,localhost,10.96.0.0/12,10.40.58.0/24,10.40.62.0/24,192.168.0.0/16"
            - name: HTTP_PROXY
              value: "http://proxy.egat.co.th:8080/"
            - name: HTTPS_PROXY
              value: "http://proxy.egat.co.th:8080/"
            - name: no_proxy
              value: "127.0.0.1,localhost,10.96.0.0/12,10.40.58.0/24,10.40.62.0/24,192.168.0.0/16"
            - name: http_proxy
              value: "http://proxy.egat.co.th:8080/"
            - name: https_proxy
              value: "http://proxy.egat.co.th:8080/"
          image: phwuts/egat-p2p-meter-api:0.0.9
          name: egat-p2p-meter-api
          ports:
            - containerPort: 4000
          resources:
            request:
              memory: "64Mi"
            limits: 
              memory: "192Mi"
      restartPolicy: Always
