apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --chart -f docker-compose-meterapi.yaml
    kompose.version: 1.25.0 (a70f80cc)
  creationTimestamp: null
  labels:
    io.kompose.service: egat-p2p-meter-api
  name: egat-p2p-meter-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: egat-p2p-meter-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --chart -f docker-compose-meterapi.yaml
        kompose.version: 1.25.0 (a70f80cc)
      creationTimestamp: null
      labels:
        io.kompose.network/egat-p2p: "true"
        io.kompose.service: egat-p2p-meter-api
    spec:
      containers:
        - env:
            - name: APP_API_KEY
              value: AIzaSyCqNmC7Pgce5a44iW8cW9HDXIFPxJDhPgQ
            - name: APP_GEOCODING_URL
              value: https://maps.googleapis.com/maps/api/geocode
            - name: HOST
              value: 0.0.0.0
            - name: MONGO_INITDB_DATABASENAME
              value: MasterDataDatabase
            - name: MONGO_INITDB_HOST
              value: masterdata-mongodb
            - name: MONGO_INITDB_PASSWORD
              value: Passw0rdEGAT
            - name: MONGO_INITDB_PORT
              value: "27017"
            - name: MONGO_INITDB_USERNAME
              value: user
            - name: PORT
              value: "4000"
          image: phwuts/egat-p2p-meter-api:0.0.3
          name: egat-p2p-meter-api
          ports:
            - containerPort: 4000
          resources: {}
      restartPolicy: Always
status: {}
