apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    apps: meterdb
  name: meterdb
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    apps: meterdb
