apiVersion: v1
kind: Service
metadata:
  name: job-mongodb-external-svc
  namespace: kafka-connect
spec:
  externalName: job-mongodb-0-external.erc-p2p.svc.cluster.local
  internalTrafficPolicy: Cluster
  sessionAffinity: None
  type: ExternalName