apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    apps: egat-p2p-reference-data-hyperledger-api-claim0
  name: egat-p2p-reference-data-hyperledger-api-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
