apiVersion: v1
kind: Service
metadata:
  name: egat-bilateral-chaincode-001
  namespace: hyperledger
spec:
  ports:
  - name: grpc
    port: 3000
    targetPort: 3000
  selector:
    app: egat-bilateral-chaincode-001
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: egat-bilateral-chaincode-001
  name: egat-bilateral-chaincode-001
  namespace: hyperledger
spec:
  selector:
    matchLabels:
      app: egat-bilateral-chaincode-001
  template:
    metadata:
      labels:
        app: egat-bilateral-chaincode-001
    spec:
      nodeSelector:
        tier: api
      containers:
      - name: egat-bilateral-chaincode-001
        image: phwuts/egat-p2p-bilateral-log-chaincode:0.0.3
        imagePullPolicy: Always
        env:
        - name: CORE_CHAINCODE_ID
          value: 'bilateral-log_0.0.1:38150cb82fccb7c7045d88791dd3e8a89b8767fcc47ada2f8c46316e954943da'
        - name: CORE_CHAINCODE_ADDRESS
          value: 0.0.0.0:3000
        ports:
        - containerPort: 3000
        resources:
            requests:
              memory: "64Mi"
            limits: 
              memory: "128Mi"
      dnsPolicy: ClusterFirst