apiVersion: v1
kind: Service
metadata:
  name: egat-pool-chaincode-003
  namespace: hyperledger
spec:
  ports:
  - name: grpc
    port: 3000
    targetPort: 3000
  selector:
    app: egat-pool-chaincode-003
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: egat-pool-chaincode-003
  name: egat-pool-chaincode-003
  namespace: hyperledger
spec:
  selector:
    matchLabels:
      app: egat-pool-chaincode-003
  template:
    metadata:
      labels:
        app: egat-pool-chaincode-003
    spec:
      containers:
      - name: egat-pool-chaincode-003
        image: phwuts/egat-p2p-pool-log-chaincode:0.0.3
        imagePullPolicy: Always
        env:
        - name: CORE_CHAINCODE_ID
          value: 'pool-log_0.0.3:ac114e2c491ee9898bd276ef8ac14691eb4c54fcffb01d38154e777ab62ede56'
        - name: CORE_CHAINCODE_ADDRESS
          value: 0.0.0.0:3000
        ports:
        - containerPort: 3000
        resources: {}
      dnsPolicy: ClusterFirst
