apiVersion: v1
kind: Service
metadata:
  name: egat-trade-chaincode-002
  namespace: hyperledger
spec:
  ports:
  - name: grpc
    port: 3000
    targetPort: 3000
  selector:
    app: egat-trade-chaincode-002
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: egat-trade-chaincode-002
  name: egat-trade-chaincode-002
  namespace: hyperledger
spec:
  selector:
    matchLabels:
      app: egat-trade-chaincode-002
  template:
    metadata:
      labels:
        app: egat-trade-chaincode-002
    spec:
      nodeSelector:
        tier: api
      containers:
      - name: egat-trade-chaincode-002
        image: phwuts/egat-p2p-trade-log-chaincode:0.0.4
        imagePullPolicy: Always
        env:
        - name: CORE_CHAINCODE_ID
          value: 'trade-log_0.0.2:9870abffe6db6504b749dbfc8eba869d8c720b773a9a37d6b0672730ae840759'
        - name: CORE_CHAINCODE_ADDRESS
          value: 0.0.0.0:3000
        ports:
        - containerPort: 3000
        resources:
            requests:
              memory: "64Mi"
            limits: 
              memory: "128Mi"
      dnsPolicy: ClusterFirst