apiVersion: v1
kind: Service
metadata:
  name: egat-trade-chaincode-003
  namespace: hyperledger
spec:
  ports:
  - name: grpc
    port: 3000
    targetPort: 3000
  selector:
    app: egat-trade-chaincode-003
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: egat-trade-chaincode-003
  name: egat-trade-chaincode-003
  namespace: hyperledger
spec:
  selector:
    matchLabels:
      app: egat-trade-chaincode-003
  template:
    metadata:
      labels:
        app: egat-trade-chaincode-003
    spec:
      nodeSelector:
        tier: api
      containers:
      - name: egat-trade-chaincode-003
        image: phwuts/egat-p2p-trade-log-chaincode:0.0.5
        imagePullPolicy: Always
        env:
        - name: CORE_CHAINCODE_ID
          value: 'trade-log_0.0.3:64f081f66aea18c3bd5f0a7a3beced42438f38bba636a9e86501f97e8976172c'
        - name: CORE_CHAINCODE_ADDRESS
          value: 0.0.0.0:3000
        ports:
        - containerPort: 3000
        resources:
            requests:
              memory: "64Mi"
            limits: 
              memory: "128Mi"
      dnsPolicy: ClusterFirst