apiVersion: v1
kind: Service
metadata:
  name: egat-reference-data-log-chaincode_001
  namespace: hyperledger
spec:
  ports:
  - name: grpc
    port: 3000
    targetPort: 3000
  selector:
    app: egat-reference-data-log-chaincode_001
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: egat-reference-data-log-chaincode_001
  name: egat-reference-data-log-chaincode_001
  namespace: hyperledger
spec:
  selector:
    matchLabels:
      app: egat-reference-data-log-chaincode_001
  template:
    metadata:
      labels:
        app: egat-reference-data-log-chaincode_001
    spec:
      containers:
      - name: egat-reference-data-log-chaincode_001
        image: phwuts/egat-p2p-reference-data-log-chaincode:0.0.1
        imagePullPolicy: Always
        env:
        - name: CORE_CHAINCODE_ID
          value: 'reference-data-log_0.0.1:0ef1c98cb0d87eedeebfa1f89a02b0e9564bb3d45f6fd945b3d9e593d87125e2'
        - name: CORE_CHAINCODE_ADDRESS
          value: 0.0.0.0:3000
        ports:
        - containerPort: 3000
        resources: {}
      dnsPolicy: ClusterFirst