apiVersion: v1
kind: Service
metadata:
  labels:
    apps: egat-p2p-mobile-trade-api
  name: egat-p2p-mobile-trade-api
spec:
  ports:
    - name: "39085"
      port: 39085
      targetPort: 3000
  selector:
    apps: egat-p2p-mobile-trade-api
status:
  loadBalancer: {}
