apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"ca-org2"},"name":"ca-org2","namespace":"hyperledger"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"ca-org2"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"labels":{"app":"ca-org2"}},"spec":{"containers":[{"args":["sh","-c","fabric-ca-server start --ca.certfile /share/crypto-config/peerOrganizations/org2/ca/ca.org2-cert.pem --ca.keyfile /share/crypto-config/peerOrganizations/org2/ca/priv_sk -b admin:adminpw -d"],"env":[{"name":"FABRIC_CA_HOME","value":"/etc/hyperledger/fabric-ca-server"},{"name":"FABRIC_CA_SERVER_CA_NAME","value":"ca-org2"},{"name":"FABRIC_CA_SERVER_TLS_CERTFILE","value":"/share/crypto-config/peerOrganizations/org2/ca/ca.org2-cert.pem"},{"name":"FABRIC_CA_SERVER_TLS_ENABLED","value":"true"},{"name":"FABRIC_CA_SERVER_TLS_KEYFILE","value":"/share/crypto-config/peerOrganizations/org2/ca/priv_sk"}],"image":"hyperledger/fabric-ca:amd64-1.4.7","name":"ca-org2","ports":[{"containerPort":7054}],"volumeMounts":[{"mountPath":"/share","name":"share-persistentdata","readOnly":true},{"mountPath":"/etc/hyperledger/fabric-ca-server","name":"ca-persistentdata"}]}],"restartPolicy":"Always","volumes":[{"name":"share-persistentdata","persistentVolumeClaim":{"claimName":"share-pvc"}},{"name":"ca-persistentdata","persistentVolumeClaim":{"claimName":"org2-ca-pvc"}}]}}}}
  creationTimestamp: "2021-11-12T09:18:33Z"
  generation: 2
  labels:
    app: ca-org2
  name: ca-org2
  namespace: hyperledger
  resourceVersion: "50127148"
  uid: 0367fdb4-19ef-4ae9-82a9-b85381a2273c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ca-org2
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ca-org2
    spec:
      containers:
      - args:
        - sh
        - -c
        - fabric-ca-server start --ca.certfile /share/crypto-config/peerOrganizations/org2/ca/ca.org2-cert.pem
          --ca.keyfile /share/crypto-config/peerOrganizations/org2/ca/priv_sk -b admin:adminpw
          -d
        env:
        - name: FABRIC_CA_HOME
          value: /etc/hyperledger/fabric-ca-server
        - name: FABRIC_CA_SERVER_CA_NAME
          value: ca-org2
        - name: FABRIC_CA_SERVER_TLS_CERTFILE
          value: /share/crypto-config/peerOrganizations/org2/ca/ca.org2-cert.pem
        - name: FABRIC_CA_SERVER_TLS_ENABLED
          value: "true"
        - name: FABRIC_CA_SERVER_TLS_KEYFILE
          value: /share/crypto-config/peerOrganizations/org2/ca/priv_sk
        image: hyperledger/fabric-ca:amd64-1.4.7
        imagePullPolicy: IfNotPresent
        name: ca-org2
        ports:
        - containerPort: 7054
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /share
          name: share-persistentdata
          readOnly: true
        - mountPath: /etc/hyperledger/fabric-ca-server
          name: ca-persistentdata
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: share-persistentdata
        persistentVolumeClaim:
          claimName: share-pvc
      - name: ca-persistentdata
        persistentVolumeClaim:
          claimName: org2-ca-pvc
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-11-12T09:18:33Z"
    lastUpdateTime: "2021-11-12T09:27:52Z"
    message: ReplicaSet "ca-org2-5fbffb59cb" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-01-25T23:41:29Z"
    lastUpdateTime: "2022-01-25T23:41:29Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
