apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"orderer0"},"name":"orderer0","namespace":"hyperledger"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"orderer0"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"labels":{"app":"orderer0"}},"spec":{"affinity":{"podAntiAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"podAffinityTerm":{"labelSelector":{"matchExpressions":[{"key":"app","operator":"In","values":["orderer1","orderer2"]}]},"topologyKey":"kubernetes.io/hostname"},"weight":1}]}},"containers":[{"args":["orderer"],"env":[{"name":"FABRIC_LOGGING_SPEC","value":"DEBUG"},{"name":"ORDERER_OPERATIONS_LISTENADDRESS","value":"0.0.0.0:8443"},{"name":"ORDERER_METRICS_PROVIDER","value":"prometheus"},{"name":"ORDERER_GENERAL_GENESISFILE","value":"/share/channel-artifacts/genesis.block"},{"name":"ORDERER_GENERAL_GENESISMETHOD","value":"file"},{"name":"ORDERER_GENERAL_LISTENADDRESS","value":"0.0.0.0"},{"name":"ORDERER_GENERAL_LOCALMSPDIR","value":"/share/crypto-config/ordererOrganizations/consortium/orderers/orderer0/msp"},{"name":"ORDERER_GENERAL_LOCALMSPID","value":"OrdererMSP"},{"name":"ORDERER_GENERAL_TLS_CERTIFICATE","value":"/share/crypto-config/ordererOrganizations/consortium/orderers/orderer0/tls/server.crt"},{"name":"ORDERER_GENERAL_TLS_ENABLED","value":"true"},{"name":"ORDERER_GENERAL_TLS_PRIVATEKEY","value":"/share/crypto-config/ordererOrganizations/consortium/orderers/orderer0/tls/server.key"},{"name":"ORDERER_GENERAL_TLS_ROOTCAS","value":"[/share/crypto-config/ordererOrganizations/consortium/orderers/orderer0/tls/ca.crt]"},{"name":"ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE","value":"/share/crypto-config/ordererOrganizations/consortium/orderers/orderer0/tls/server.crt"},{"name":"ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY","value":"/share/crypto-config/ordererOrganizations/consortium/orderers/orderer0/tls/server.key"},{"name":"ORDERER_GENERAL_CLUSTER_ROOTCAS","value":"[/share/crypto-config/ordererOrganizations/consortium/orderers/orderer0/tls/ca.crt]"}],"image":"hyperledger/fabric-orderer:amd64-2.2.0","name":"orderer","ports":[{"containerPort":7050},{"containerPort":8443}],"volumeMounts":[{"mountPath":"/var/hyperledger/production","name":"orderer-persistentdata"},{"mountPath":"/share","name":"share-persistentdata"}],"workingDir":"/opt/gopath/src/github.com/hyperledger/fabric"}],"restartPolicy":"Always","volumes":[{"name":"orderer-persistentdata","persistentVolumeClaim":{"claimName":"orderer0-pvc"}},{"name":"share-persistentdata","persistentVolumeClaim":{"claimName":"share-pvc"}}]}}}}
  creationTimestamp: "2021-11-12T08:51:02Z"
  generation: 1
  labels:
    app: orderer0
  name: orderer0
  namespace: hyperledger
  resourceVersion: "42536320"
  uid: 903f2972-1d8c-49c0-9c9d-71a411226d36
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: orderer0
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: orderer0
    spec:
      nodeSelector:
        tier: api
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - orderer1
                  - orderer2
              topologyKey: kubernetes.io/hostname
            weight: 1
      containers:
      - args:
        - orderer
        env:
        - name: FABRIC_LOGGING_SPEC
          value: DEBUG
        - name: ORDERER_OPERATIONS_LISTENADDRESS
          value: 0.0.0.0:8443
        - name: ORDERER_METRICS_PROVIDER
          value: prometheus
        - name: ORDERER_GENERAL_GENESISFILE
          value: /share/channel-artifacts/genesis.block
        - name: ORDERER_GENERAL_GENESISMETHOD
          value: file
        - name: ORDERER_GENERAL_LISTENADDRESS
          value: 0.0.0.0
        - name: ORDERER_GENERAL_LOCALMSPDIR
          value: /share/crypto-config/ordererOrganizations/consortium/orderers/orderer0/msp
        - name: ORDERER_GENERAL_LOCALMSPID
          value: OrdererMSP
        - name: ORDERER_GENERAL_TLS_CERTIFICATE
          value: /share/crypto-config/ordererOrganizations/consortium/orderers/orderer0/tls/server.crt
        - name: ORDERER_GENERAL_TLS_ENABLED
          value: "true"
        - name: ORDERER_GENERAL_TLS_PRIVATEKEY
          value: /share/crypto-config/ordererOrganizations/consortium/orderers/orderer0/tls/server.key
        - name: ORDERER_GENERAL_TLS_ROOTCAS
          value: '[/share/crypto-config/ordererOrganizations/consortium/orderers/orderer0/tls/ca.crt]'
        - name: ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE
          value: /share/crypto-config/ordererOrganizations/consortium/orderers/orderer0/tls/server.crt
        - name: ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY
          value: /share/crypto-config/ordererOrganizations/consortium/orderers/orderer0/tls/server.key
        - name: ORDERER_GENERAL_CLUSTER_ROOTCAS
          value: '[/share/crypto-config/ordererOrganizations/consortium/orderers/orderer0/tls/ca.crt]'
        image: hyperledger/fabric-orderer:amd64-2.2.0
        imagePullPolicy: IfNotPresent
        name: orderer
        ports:
        - containerPort: 7050
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/hyperledger/production
          name: orderer-persistentdata
        - mountPath: /share
          name: share-persistentdata
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: orderer-persistentdata
        persistentVolumeClaim:
          claimName: orderer0-pvc
      - name: share-persistentdata
        persistentVolumeClaim:
          claimName: share-pvc
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-11-12T08:51:02Z"
    lastUpdateTime: "2021-11-12T08:51:25Z"
    message: ReplicaSet "orderer0-7bcd9b564c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-01-05T04:06:42Z"
    lastUpdateTime: "2022-01-05T04:06:42Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
