apiVersion: v1
kind: Service
metadata:
  labels:
    apps: egat-p2p-mobile-register-api
  name: egat-p2p-mobile-register-api
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    apps: egat-p2p-mobile-register-api

