apiVersion: v1
kind: Service
metadata:
  name: egat-trade-chaincode-002
  namespace: hyperledger
spec:
  ports:
  - name: grpc
    port: 3000
    targetPort: 3000
  selector:
    app: egat-trade-chaincode-002
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: egat-trade-chaincode-002
  name: egat-trade-chaincode-002
  namespace: hyperledger
spec:
  selector:
    matchLabels:
      app: egat-trade-chaincode-002
  template:
    metadata:
      labels:
        app: egat-trade-chaincode-002
    spec:
      containers:
      - name: egat-trade-chaincode-002
        image: phwuts/egat-p2p-trade-log-chaincode:0.0.1
        imagePullPolicy: Always
        env:
        - name: CORE_CHAINCODE_ID
          value: 'egat-trade_0.0.1:xxxxxxx'
        - name: CORE_CHAINCODE_ADDRESS
          value: 0.0.0.0:3000
        ports:
        - containerPort: 3000
        resources: {}
      dnsPolicy: ClusterFirst