apiVersion: v1
kind: Service
metadata:
  labels:
    apps: egat-p2p-mobile-login-api
  name: egat-p2p-mobile-login-api
spec:
  ports:
    - name: "3001"
      port: 3001
      targetPort: 3001
  selector:
    apps: egat-p2p-mobile-login-api

