apiVersion: v1
kind: Service
metadata:
  labels:
    apps: egat-p2p-reference-data-hyperledger-api
  name: egat-p2p-reference-data-hyperledger-api
spec:
  ports:
    - name: "5005"
      port: 5005
      targetPort: 5005
  selector:
    apps: egat-p2p-reference-data-hyperledger-api
status:
  loadBalancer: {}
