apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    apps: egat-p2p-reference-data-hyperledger-keystore
  name: egat-p2p-reference-data-hyperledger-keystore
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
