apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    apps: egat-p2p-mobile-pool-api
  name: egat-p2p-mobile-pool-api
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: egat-p2p-mobile-pool-api
  strategy: {}
  template:
    metadata:
      labels:
        apps: egat-p2p-mobile-pool-api
    spec:
      nodeSelector:
        tier: api
      containers:
        - env:
            - name: MONGO_DATABASE
              value: PoolDatabase
            - name: MONGO_HOST
              value: pool-mongodb-0-external
            - name: MONGO_PASSWORD
              value: Passw0rdEGAT
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USER
              value: user
            - name: NODE_ENV
              value: development
            - name: TRADE_API_ENDPOINT
              value: http://egat-p2p-trade-job-api:39085
            - name: METER_API_ENDPOINT
              value: http://egat-p2p-meter-api:4000
            - name: REFERENCE_API_ENDPOINT
              value: http://egat-p2p-web-admin-ref-management-api:3005
          image: lenkunz/egat-p2p-pool:1.9.0-beta
          name: egat-p2p-mobile-pool-api
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
            limits: 
              memory: "192Mi"
      restartPolicy: Always
