apiVersion: v1
kind: Service
metadata:
  labels:
    app: egat-p2p-mobile-trade-hyperledger-api
  name: egat-p2p-mobile-trade-hyperledger-api
spec:
  ports:
    - name: "5008"
      port: 5008
      targetPort: 5008
  selector:
    app: egat-p2p-mobile-trade-hyperledger-api

