apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: egat-p2p-mobile-trade-hyperledger-keystore
  name: egat-p2p-mobile-trade-hyperledger-keystore
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
