apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    banzaicloud.com/last-applied: '{"metadata":{"labels":{"app":"rook-ceph-mds","ceph-version":"16.2.6-0","ceph_daemon_id":"myfs-b","ceph_daemon_type":"mds","mds":"myfs-b","rook-version":"v1.7.5","rook_cluster":"rook-ceph","rook_file_system":"myfs"},"name":"rook-ceph-mds-myfs-b","namespace":"rook-ceph","ownerReferences":[{"apiVersion":"ceph.rook.io/v1","blockOwnerDeletion":true,"controller":true,"kind":"CephFilesystem","name":"myfs","uid":"1952ae50-effa-4e62-b6f3-8d572cc5841b"}]},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"rook-ceph-mds","ceph_daemon_id":"myfs-b","mds":"myfs-b","rook_cluster":"rook-ceph","rook_file_system":"myfs"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"labels":{"app":"rook-ceph-mds","ceph_daemon_id":"myfs-b","ceph_daemon_type":"mds","mds":"myfs-b","rook_cluster":"rook-ceph","rook_file_system":"myfs"},"name":"rook-ceph-mds-myfs-b","namespace":"rook-ceph"},"spec":{"affinity":{"podAntiAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"podAffinityTerm":{"labelSelector":{"matchExpressions":[{"key":"app","operator":"In","values":["rook-ceph-mds"]}]},"topologyKey":"topology.kubernetes.io/zone"},"weight":100}],"requiredDuringSchedulingIgnoredDuringExecution":[{"labelSelector":{"matchExpressions":[{"key":"app","operator":"In","values":["rook-ceph-mds"]}]},"topologyKey":"kubernetes.io/hostname"}]}},"containers":[{"args":["--fsid=6023a4fd-488a-43e9-bc0b-d18d8a5609bb","--keyring=/etc/ceph/keyring-store/keyring","--log-to-stderr=true","--err-to-stderr=true","--mon-cluster-log-to-stderr=true","--log-stderr-prefix=debug
      ","--default-log-to-file=false","--default-mon-cluster-log-to-file=false","--mon-host=$(ROOK_CEPH_MON_HOST)","--mon-initial-members=$(ROOK_CEPH_MON_INITIAL_MEMBERS)","--id=myfs-b","--setuser=ceph","--setgroup=ceph","--foreground","--public-addr=$(ROOK_POD_IP)"],"command":["ceph-mds"],"env":[{"name":"CONTAINER_IMAGE","value":"quay.io/ceph/ceph:v16.2.6"},{"name":"POD_NAME","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}},{"name":"POD_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}},{"name":"NODE_NAME","valueFrom":{"fieldRef":{"fieldPath":"spec.nodeName"}}},{"name":"POD_MEMORY_LIMIT","valueFrom":{"resourceFieldRef":{"divisor":"0","resource":"limits.memory"}}},{"name":"POD_MEMORY_REQUEST","valueFrom":{"resourceFieldRef":{"divisor":"0","resource":"requests.memory"}}},{"name":"POD_CPU_LIMIT","valueFrom":{"resourceFieldRef":{"divisor":"1","resource":"limits.cpu"}}},{"name":"POD_CPU_REQUEST","valueFrom":{"resourceFieldRef":{"divisor":"0","resource":"requests.cpu"}}},{"name":"ROOK_CEPH_MON_HOST","valueFrom":{"secretKeyRef":{"key":"mon_host","name":"rook-ceph-config"}}},{"name":"ROOK_CEPH_MON_INITIAL_MEMBERS","valueFrom":{"secretKeyRef":{"key":"mon_initial_members","name":"rook-ceph-config"}}},{"name":"ROOK_POD_IP","valueFrom":{"fieldRef":{"fieldPath":"status.podIP"}}}],"image":"quay.io/ceph/ceph:v16.2.6","livenessProbe":{"exec":{"command":["env","-i","sh","-c","ceph
      --admin-daemon /run/ceph/ceph-mds.myfs-b.asok status"]},"initialDelaySeconds":10},"name":"mds","resources":{},"volumeMounts":[{"mountPath":"/etc/ceph","name":"rook-config-override","readOnly":true},{"mountPath":"/etc/ceph/keyring-store/","name":"rook-ceph-mds-myfs-b-keyring","readOnly":true},{"mountPath":"/var/log/ceph","name":"rook-ceph-log"},{"mountPath":"/var/lib/ceph/crash","name":"rook-ceph-crash"},{"mountPath":"/var/lib/ceph/mds/ceph-myfs-b","name":"ceph-daemon-data"}],"workingDir":"/var/log/ceph"}],"initContainers":[{"args":["--verbose","--recursive","ceph:ceph","/var/log/ceph","/var/lib/ceph/crash","/var/lib/ceph/mds/ceph-myfs-b"],"command":["chown"],"image":"quay.io/ceph/ceph:v16.2.6","name":"chown-container-data-dir","resources":{},"volumeMounts":[{"mountPath":"/etc/ceph","name":"rook-config-override","readOnly":true},{"mountPath":"/etc/ceph/keyring-store/","name":"rook-ceph-mds-myfs-b-keyring","readOnly":true},{"mountPath":"/var/log/ceph","name":"rook-ceph-log"},{"mountPath":"/var/lib/ceph/crash","name":"rook-ceph-crash"},{"mountPath":"/var/lib/ceph/mds/ceph-myfs-b","name":"ceph-daemon-data"}]}],"restartPolicy":"Always","tolerations":[{"effect":"NoExecute","key":"node.kubernetes.io/unreachable","operator":"Exists","tolerationSeconds":5}],"volumes":[{"name":"rook-config-override","projected":{"sources":[{"configMap":{"items":[{"key":"config","mode":292,"path":"ceph.conf"}],"name":"rook-config-override"}}]}},{"name":"rook-ceph-mds-myfs-b-keyring","secret":{"secretName":"rook-ceph-mds-myfs-b-keyring"}},{"hostPath":{"path":"/var/lib/rook/rook-ceph/log"},"name":"rook-ceph-log"},{"hostPath":{"path":"/var/lib/rook/rook-ceph/crash"},"name":"rook-ceph-crash"},{"emptyDir":{},"name":"ceph-daemon-data"}]}}},"status":{}}'
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: "2021-09-23T04:50:57Z"
  generation: 3
  labels:
    app: rook-ceph-mds
    ceph-version: 16.2.6-0
    ceph_daemon_id: myfs-b
    ceph_daemon_type: mds
    mds: myfs-b
    rook-version: v1.7.5
    rook_cluster: rook-ceph
    rook_file_system: myfs
  name: rook-ceph-mds-myfs-b
  namespace: rook-ceph
  ownerReferences:
  - apiVersion: ceph.rook.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: CephFilesystem
    name: myfs
    uid: 1952ae50-effa-4e62-b6f3-8d572cc5841b
  resourceVersion: "42916252"
  uid: 224106e2-712a-4578-bea0-371de9df6a10
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rook-ceph-mds
      ceph_daemon_id: myfs-b
      mds: myfs-b
      rook_cluster: rook-ceph
      rook_file_system: myfs
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rook-ceph-mds
        ceph_daemon_id: myfs-b
        ceph_daemon_type: mds
        mds: myfs-b
        rook_cluster: rook-ceph
        rook_file_system: myfs
      name: rook-ceph-mds-myfs-b
      namespace: rook-ceph
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - rook-ceph-mds
              topologyKey: topology.kubernetes.io/zone
            weight: 100
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - rook-ceph-mds
            topologyKey: kubernetes.io/hostname
      containers:
      - args:
        - --fsid=6023a4fd-488a-43e9-bc0b-d18d8a5609bb
        - --keyring=/etc/ceph/keyring-store/keyring
        - --log-to-stderr=true
        - --err-to-stderr=true
        - --mon-cluster-log-to-stderr=true
        - '--log-stderr-prefix=debug '
        - --default-log-to-file=false
        - --default-mon-cluster-log-to-file=false
        - --mon-host=$(ROOK_CEPH_MON_HOST)
        - --mon-initial-members=$(ROOK_CEPH_MON_INITIAL_MEMBERS)
        - --id=myfs-b
        - --setuser=ceph
        - --setgroup=ceph
        - --foreground
        - --public-addr=$(ROOK_POD_IP)
        command:
        - ceph-mds
        env:
        - name: CONTAINER_IMAGE
          value: quay.io/ceph/ceph:v16.2.6
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_MEMORY_LIMIT
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: limits.memory
        - name: POD_MEMORY_REQUEST
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: requests.memory
        - name: POD_CPU_LIMIT
          valueFrom:
            resourceFieldRef:
              divisor: "1"
              resource: limits.cpu
        - name: POD_CPU_REQUEST
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: requests.cpu
        - name: ROOK_CEPH_MON_HOST
          valueFrom:
            secretKeyRef:
              key: mon_host
              name: rook-ceph-config
        - name: ROOK_CEPH_MON_INITIAL_MEMBERS
          valueFrom:
            secretKeyRef:
              key: mon_initial_members
              name: rook-ceph-config
        - name: ROOK_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: quay.io/ceph/ceph:v16.2.6
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - env
            - -i
            - sh
            - -c
            - ceph --admin-daemon /run/ceph/ceph-mds.myfs-b.asok status
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: mds
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/ceph
          name: rook-config-override
          readOnly: true
        - mountPath: /etc/ceph/keyring-store/
          name: rook-ceph-mds-myfs-b-keyring
          readOnly: true
        - mountPath: /var/log/ceph
          name: rook-ceph-log
        - mountPath: /var/lib/ceph/crash
          name: rook-ceph-crash
        - mountPath: /var/lib/ceph/mds/ceph-myfs-b
          name: ceph-daemon-data
        workingDir: /var/log/ceph
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - --verbose
        - --recursive
        - ceph:ceph
        - /var/log/ceph
        - /var/lib/ceph/crash
        - /var/lib/ceph/mds/ceph-myfs-b
        command:
        - chown
        image: quay.io/ceph/ceph:v16.2.6
        imagePullPolicy: IfNotPresent
        name: chown-container-data-dir
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/ceph
          name: rook-config-override
          readOnly: true
        - mountPath: /etc/ceph/keyring-store/
          name: rook-ceph-mds-myfs-b-keyring
          readOnly: true
        - mountPath: /var/log/ceph
          name: rook-ceph-log
        - mountPath: /var/lib/ceph/crash
          name: rook-ceph-crash
        - mountPath: /var/lib/ceph/mds/ceph-myfs-b
          name: ceph-daemon-data
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 5
      volumes:
      - name: rook-config-override
        projected:
          defaultMode: 420
          sources:
          - configMap:
              items:
              - key: config
                mode: 292
                path: ceph.conf
              name: rook-config-override
      - name: rook-ceph-mds-myfs-b-keyring
        secret:
          defaultMode: 420
          secretName: rook-ceph-mds-myfs-b-keyring
      - hostPath:
          path: /var/lib/rook/rook-ceph/log
          type: ""
        name: rook-ceph-log
      - hostPath:
          path: /var/lib/rook/rook-ceph/crash
          type: ""
        name: rook-ceph-crash
      - emptyDir: {}
        name: ceph-daemon-data
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-09-23T04:50:57Z"
    lastUpdateTime: "2022-01-06T02:44:14Z"
    message: ReplicaSet "rook-ceph-mds-myfs-b-7b49bd5499" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-01-06T03:43:17Z"
    lastUpdateTime: "2022-01-06T03:43:17Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
