apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    banzaicloud.com/last-applied: '{"metadata":{"labels":{"app":"rook-ceph-mgr","ceph-version":"16.2.6-0","ceph_daemon_id":"a","ceph_daemon_type":"mgr","instance":"a","mgr":"a","rook-version":"v1.7.5","rook_cluster":"rook-ceph"},"name":"rook-ceph-mgr-a","namespace":"rook-ceph","ownerReferences":[{"apiVersion":"ceph.rook.io/v1","blockOwnerDeletion":true,"controller":true,"kind":"CephCluster","name":"rook-ceph","uid":"6cef12f2-e7e1-4af1-a84b-202658a6dbf3"}]},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"rook-ceph-mgr","ceph_daemon_id":"a","instance":"a","mgr":"a","rook_cluster":"rook-ceph"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"annotations":{"prometheus.io/port":"9283","prometheus.io/scrape":"true"},"labels":{"app":"rook-ceph-mgr","ceph_daemon_id":"a","ceph_daemon_type":"mgr","instance":"a","mgr":"a","rook_cluster":"rook-ceph"},"name":"rook-ceph-mgr-a"},"spec":{"affinity":{},"containers":[{"args":["--fsid=6023a4fd-488a-43e9-bc0b-d18d8a5609bb","--keyring=/etc/ceph/keyring-store/keyring","--log-to-stderr=true","--err-to-stderr=true","--mon-cluster-log-to-stderr=true","--log-stderr-prefix=debug
      ","--default-log-to-file=false","--default-mon-cluster-log-to-file=false","--mon-host=$(ROOK_CEPH_MON_HOST)","--mon-initial-members=$(ROOK_CEPH_MON_INITIAL_MEMBERS)","--id=a","--setuser=ceph","--setgroup=ceph","--client-mount-uid=0","--client-mount-gid=0","--foreground","--public-addr=$(ROOK_POD_IP)"],"command":["ceph-mgr"],"env":[{"name":"CONTAINER_IMAGE","value":"quay.io/ceph/ceph:v16.2.6"},{"name":"POD_NAME","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}},{"name":"POD_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}},{"name":"NODE_NAME","valueFrom":{"fieldRef":{"fieldPath":"spec.nodeName"}}},{"name":"POD_MEMORY_LIMIT","valueFrom":{"resourceFieldRef":{"divisor":"0","resource":"limits.memory"}}},{"name":"POD_MEMORY_REQUEST","valueFrom":{"resourceFieldRef":{"divisor":"0","resource":"requests.memory"}}},{"name":"POD_CPU_LIMIT","valueFrom":{"resourceFieldRef":{"divisor":"1","resource":"limits.cpu"}}},{"name":"POD_CPU_REQUEST","valueFrom":{"resourceFieldRef":{"divisor":"0","resource":"requests.cpu"}}},{"name":"ROOK_CEPH_MON_HOST","valueFrom":{"secretKeyRef":{"key":"mon_host","name":"rook-ceph-config"}}},{"name":"ROOK_CEPH_MON_INITIAL_MEMBERS","valueFrom":{"secretKeyRef":{"key":"mon_initial_members","name":"rook-ceph-config"}}},{"name":"ROOK_OPERATOR_NAMESPACE","value":"rook-ceph"},{"name":"ROOK_CEPH_CLUSTER_CRD_VERSION","value":"v1"},{"name":"ROOK_CEPH_CLUSTER_CRD_NAME","value":"rook-ceph"},{"name":"ROOK_POD_IP","valueFrom":{"fieldRef":{"fieldPath":"status.podIP"}}}],"image":"quay.io/ceph/ceph:v16.2.6","livenessProbe":{"exec":{"command":["env","-i","sh","-c","ceph
      --admin-daemon /run/ceph/ceph-mgr.a.asok status"]},"initialDelaySeconds":10},"name":"mgr","ports":[{"containerPort":6800,"name":"mgr","protocol":"TCP"},{"containerPort":9283,"name":"http-metrics","protocol":"TCP"},{"containerPort":8443,"name":"dashboard","protocol":"TCP"}],"resources":{},"volumeMounts":[{"mountPath":"/etc/ceph","name":"rook-config-override","readOnly":true},{"mountPath":"/etc/ceph/keyring-store/","name":"rook-ceph-mgr-a-keyring","readOnly":true},{"mountPath":"/var/log/ceph","name":"rook-ceph-log"},{"mountPath":"/var/lib/ceph/crash","name":"rook-ceph-crash"},{"mountPath":"/var/lib/ceph/mgr/ceph-a","name":"ceph-daemon-data"}],"workingDir":"/var/log/ceph"}],"initContainers":[{"args":["--verbose","--recursive","ceph:ceph","/var/log/ceph","/var/lib/ceph/crash","/var/lib/ceph/mgr/ceph-a"],"command":["chown"],"image":"quay.io/ceph/ceph:v16.2.6","name":"chown-container-data-dir","resources":{},"volumeMounts":[{"mountPath":"/etc/ceph","name":"rook-config-override","readOnly":true},{"mountPath":"/etc/ceph/keyring-store/","name":"rook-ceph-mgr-a-keyring","readOnly":true},{"mountPath":"/var/log/ceph","name":"rook-ceph-log"},{"mountPath":"/var/lib/ceph/crash","name":"rook-ceph-crash"},{"mountPath":"/var/lib/ceph/mgr/ceph-a","name":"ceph-daemon-data"}]}],"restartPolicy":"Always","serviceAccountName":"rook-ceph-mgr","tolerations":[{"effect":"NoExecute","key":"node.kubernetes.io/unreachable","operator":"Exists","tolerationSeconds":5}],"volumes":[{"name":"rook-config-override","projected":{"sources":[{"configMap":{"items":[{"key":"config","mode":292,"path":"ceph.conf"}],"name":"rook-config-override"}}]}},{"name":"rook-ceph-mgr-a-keyring","secret":{"secretName":"rook-ceph-mgr-a-keyring"}},{"hostPath":{"path":"/var/lib/rook/rook-ceph/log"},"name":"rook-ceph-log"},{"hostPath":{"path":"/var/lib/rook/rook-ceph/crash"},"name":"rook-ceph-crash"},{"emptyDir":{},"name":"ceph-daemon-data"}]}}},"status":{}}'
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: "2021-09-22T09:05:13Z"
  generation: 3
  labels:
    app: rook-ceph-mgr
    ceph-version: 16.2.6-0
    ceph_daemon_id: a
    ceph_daemon_type: mgr
    instance: a
    mgr: a
    rook-version: v1.7.5
    rook_cluster: rook-ceph
  name: rook-ceph-mgr-a
  namespace: rook-ceph
  ownerReferences:
  - apiVersion: ceph.rook.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: CephCluster
    name: rook-ceph
    uid: 6cef12f2-e7e1-4af1-a84b-202658a6dbf3
  resourceVersion: "42919902"
  uid: 4fc39e44-954d-4469-9223-139cae171478
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rook-ceph-mgr
      ceph_daemon_id: a
      instance: a
      mgr: a
      rook_cluster: rook-ceph
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/port: "9283"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: rook-ceph-mgr
        ceph_daemon_id: a
        ceph_daemon_type: mgr
        instance: a
        mgr: a
        rook_cluster: rook-ceph
      name: rook-ceph-mgr-a
    spec:
      affinity: {}
      containers:
      - args:
        - --fsid=6023a4fd-488a-43e9-bc0b-d18d8a5609bb
        - --keyring=/etc/ceph/keyring-store/keyring
        - --log-to-stderr=true
        - --err-to-stderr=true
        - --mon-cluster-log-to-stderr=true
        - '--log-stderr-prefix=debug '
        - --default-log-to-file=false
        - --default-mon-cluster-log-to-file=false
        - --mon-host=$(ROOK_CEPH_MON_HOST)
        - --mon-initial-members=$(ROOK_CEPH_MON_INITIAL_MEMBERS)
        - --id=a
        - --setuser=ceph
        - --setgroup=ceph
        - --client-mount-uid=0
        - --client-mount-gid=0
        - --foreground
        - --public-addr=$(ROOK_POD_IP)
        command:
        - ceph-mgr
        env:
        - name: CONTAINER_IMAGE
          value: quay.io/ceph/ceph:v16.2.6
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_MEMORY_LIMIT
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: limits.memory
        - name: POD_MEMORY_REQUEST
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: requests.memory
        - name: POD_CPU_LIMIT
          valueFrom:
            resourceFieldRef:
              divisor: "1"
              resource: limits.cpu
        - name: POD_CPU_REQUEST
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: requests.cpu
        - name: ROOK_CEPH_MON_HOST
          valueFrom:
            secretKeyRef:
              key: mon_host
              name: rook-ceph-config
        - name: ROOK_CEPH_MON_INITIAL_MEMBERS
          valueFrom:
            secretKeyRef:
              key: mon_initial_members
              name: rook-ceph-config
        - name: ROOK_OPERATOR_NAMESPACE
          value: rook-ceph
        - name: ROOK_CEPH_CLUSTER_CRD_VERSION
          value: v1
        - name: ROOK_CEPH_CLUSTER_CRD_NAME
          value: rook-ceph
        - name: ROOK_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: quay.io/ceph/ceph:v16.2.6
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - env
            - -i
            - sh
            - -c
            - ceph --admin-daemon /run/ceph/ceph-mgr.a.asok status
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: mgr
        ports:
        - containerPort: 6800
          name: mgr
          protocol: TCP
        - containerPort: 9283
          name: http-metrics
          protocol: TCP
        - containerPort: 8443
          name: dashboard
          protocol: TCP
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/ceph
          name: rook-config-override
          readOnly: true
        - mountPath: /etc/ceph/keyring-store/
          name: rook-ceph-mgr-a-keyring
          readOnly: true
        - mountPath: /var/log/ceph
          name: rook-ceph-log
        - mountPath: /var/lib/ceph/crash
          name: rook-ceph-crash
        - mountPath: /var/lib/ceph/mgr/ceph-a
          name: ceph-daemon-data
        workingDir: /var/log/ceph
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - --verbose
        - --recursive
        - ceph:ceph
        - /var/log/ceph
        - /var/lib/ceph/crash
        - /var/lib/ceph/mgr/ceph-a
        command:
        - chown
        image: quay.io/ceph/ceph:v16.2.6
        imagePullPolicy: IfNotPresent
        name: chown-container-data-dir
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/ceph
          name: rook-config-override
          readOnly: true
        - mountPath: /etc/ceph/keyring-store/
          name: rook-ceph-mgr-a-keyring
          readOnly: true
        - mountPath: /var/log/ceph
          name: rook-ceph-log
        - mountPath: /var/lib/ceph/crash
          name: rook-ceph-crash
        - mountPath: /var/lib/ceph/mgr/ceph-a
          name: ceph-daemon-data
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: rook-ceph-mgr
      serviceAccountName: rook-ceph-mgr
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 5
      volumes:
      - name: rook-config-override
        projected:
          defaultMode: 420
          sources:
          - configMap:
              items:
              - key: config
                mode: 292
                path: ceph.conf
              name: rook-config-override
      - name: rook-ceph-mgr-a-keyring
        secret:
          defaultMode: 420
          secretName: rook-ceph-mgr-a-keyring
      - hostPath:
          path: /var/lib/rook/rook-ceph/log
          type: ""
        name: rook-ceph-log
      - hostPath:
          path: /var/lib/rook/rook-ceph/crash
          type: ""
        name: rook-ceph-crash
      - emptyDir: {}
        name: ceph-daemon-data
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-09-22T09:05:13Z"
    lastUpdateTime: "2022-01-06T02:46:27Z"
    message: ReplicaSet "rook-ceph-mgr-a-766d8d567c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-01-06T03:51:35Z"
    lastUpdateTime: "2022-01-06T03:51:35Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
