apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    banzaicloud.com/last-applied: '{"metadata":{"labels":{"app":"rook-ceph-mon","ceph-version":"16.2.6-0","ceph_daemon_id":"c","ceph_daemon_type":"mon","mon":"c","mon_cluster":"rook-ceph","rook-version":"v1.7.5","rook_cluster":"rook-ceph"},"name":"rook-ceph-mon-c","namespace":"rook-ceph","ownerReferences":[{"apiVersion":"ceph.rook.io/v1","blockOwnerDeletion":true,"controller":true,"kind":"CephCluster","name":"rook-ceph","uid":"6cef12f2-e7e1-4af1-a84b-202658a6dbf3"}]},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"rook-ceph-mon","ceph_daemon_id":"c","mon":"c","mon_cluster":"rook-ceph","rook_cluster":"rook-ceph"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"labels":{"app":"rook-ceph-mon","ceph_daemon_id":"c","ceph_daemon_type":"mon","mon":"c","mon_cluster":"rook-ceph","rook_cluster":"rook-ceph"},"name":"rook-ceph-mon-c","namespace":"rook-ceph"},"spec":{"affinity":{},"containers":[{"args":["--fsid=6023a4fd-488a-43e9-bc0b-d18d8a5609bb","--keyring=/etc/ceph/keyring-store/keyring","--log-to-stderr=true","--err-to-stderr=true","--mon-cluster-log-to-stderr=true","--log-stderr-prefix=debug
      ","--default-log-to-file=false","--default-mon-cluster-log-to-file=false","--mon-host=$(ROOK_CEPH_MON_HOST)","--mon-initial-members=$(ROOK_CEPH_MON_INITIAL_MEMBERS)","--id=c","--setuser=ceph","--setgroup=ceph","--foreground","--public-addr=10.101.38.8","--setuser-match-path=/var/lib/ceph/mon/ceph-c/store.db","--public-bind-addr=$(ROOK_POD_IP)"],"command":["ceph-mon"],"env":[{"name":"CONTAINER_IMAGE","value":"quay.io/ceph/ceph:v16.2.6"},{"name":"POD_NAME","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}},{"name":"POD_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}},{"name":"NODE_NAME","valueFrom":{"fieldRef":{"fieldPath":"spec.nodeName"}}},{"name":"POD_MEMORY_LIMIT","valueFrom":{"resourceFieldRef":{"divisor":"0","resource":"limits.memory"}}},{"name":"POD_MEMORY_REQUEST","valueFrom":{"resourceFieldRef":{"divisor":"0","resource":"requests.memory"}}},{"name":"POD_CPU_LIMIT","valueFrom":{"resourceFieldRef":{"divisor":"1","resource":"limits.cpu"}}},{"name":"POD_CPU_REQUEST","valueFrom":{"resourceFieldRef":{"divisor":"0","resource":"requests.cpu"}}},{"name":"ROOK_CEPH_MON_HOST","valueFrom":{"secretKeyRef":{"key":"mon_host","name":"rook-ceph-config"}}},{"name":"ROOK_CEPH_MON_INITIAL_MEMBERS","valueFrom":{"secretKeyRef":{"key":"mon_initial_members","name":"rook-ceph-config"}}},{"name":"ROOK_POD_IP","valueFrom":{"fieldRef":{"fieldPath":"status.podIP"}}}],"image":"quay.io/ceph/ceph:v16.2.6","livenessProbe":{"exec":{"command":["env","-i","sh","-c","ceph
      --admin-daemon /run/ceph/ceph-mon.c.asok mon_status"]},"initialDelaySeconds":10},"name":"mon","ports":[{"containerPort":6789,"name":"tcp-msgr1","protocol":"TCP"}],"resources":{},"volumeMounts":[{"mountPath":"/etc/ceph","name":"rook-config-override","readOnly":true},{"mountPath":"/etc/ceph/keyring-store/","name":"rook-ceph-mons-keyring","readOnly":true},{"mountPath":"/var/log/ceph","name":"rook-ceph-log"},{"mountPath":"/var/lib/ceph/crash","name":"rook-ceph-crash"},{"mountPath":"/var/lib/ceph/mon/ceph-c","name":"ceph-daemon-data"}],"workingDir":"/var/log/ceph"}],"initContainers":[{"args":["--verbose","--recursive","ceph:ceph","/var/log/ceph","/var/lib/ceph/crash","/var/lib/ceph/mon/ceph-c"],"command":["chown"],"image":"quay.io/ceph/ceph:v16.2.6","name":"chown-container-data-dir","resources":{},"volumeMounts":[{"mountPath":"/etc/ceph","name":"rook-config-override","readOnly":true},{"mountPath":"/etc/ceph/keyring-store/","name":"rook-ceph-mons-keyring","readOnly":true},{"mountPath":"/var/log/ceph","name":"rook-ceph-log"},{"mountPath":"/var/lib/ceph/crash","name":"rook-ceph-crash"},{"mountPath":"/var/lib/ceph/mon/ceph-c","name":"ceph-daemon-data"}]},{"args":["--fsid=6023a4fd-488a-43e9-bc0b-d18d8a5609bb","--keyring=/etc/ceph/keyring-store/keyring","--log-to-stderr=true","--err-to-stderr=true","--mon-cluster-log-to-stderr=true","--log-stderr-prefix=debug
      ","--default-log-to-file=false","--default-mon-cluster-log-to-file=false","--mon-host=$(ROOK_CEPH_MON_HOST)","--mon-initial-members=$(ROOK_CEPH_MON_INITIAL_MEMBERS)","--id=c","--setuser=ceph","--setgroup=ceph","--public-addr=10.101.38.8","--mkfs"],"command":["ceph-mon"],"env":[{"name":"CONTAINER_IMAGE","value":"quay.io/ceph/ceph:v16.2.6"},{"name":"POD_NAME","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}},{"name":"POD_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}},{"name":"NODE_NAME","valueFrom":{"fieldRef":{"fieldPath":"spec.nodeName"}}},{"name":"POD_MEMORY_LIMIT","valueFrom":{"resourceFieldRef":{"divisor":"0","resource":"limits.memory"}}},{"name":"POD_MEMORY_REQUEST","valueFrom":{"resourceFieldRef":{"divisor":"0","resource":"requests.memory"}}},{"name":"POD_CPU_LIMIT","valueFrom":{"resourceFieldRef":{"divisor":"1","resource":"limits.cpu"}}},{"name":"POD_CPU_REQUEST","valueFrom":{"resourceFieldRef":{"divisor":"0","resource":"requests.cpu"}}},{"name":"ROOK_CEPH_MON_HOST","valueFrom":{"secretKeyRef":{"key":"mon_host","name":"rook-ceph-config"}}},{"name":"ROOK_CEPH_MON_INITIAL_MEMBERS","valueFrom":{"secretKeyRef":{"key":"mon_initial_members","name":"rook-ceph-config"}}}],"image":"quay.io/ceph/ceph:v16.2.6","name":"init-mon-fs","resources":{},"volumeMounts":[{"mountPath":"/etc/ceph","name":"rook-config-override","readOnly":true},{"mountPath":"/etc/ceph/keyring-store/","name":"rook-ceph-mons-keyring","readOnly":true},{"mountPath":"/var/log/ceph","name":"rook-ceph-log"},{"mountPath":"/var/lib/ceph/crash","name":"rook-ceph-crash"},{"mountPath":"/var/lib/ceph/mon/ceph-c","name":"ceph-daemon-data"}]}],"nodeSelector":{"kubernetes.io/hostname":"ikp-p2p-worker1"},"restartPolicy":"Always","volumes":[{"name":"rook-config-override","projected":{"sources":[{"configMap":{"items":[{"key":"config","mode":292,"path":"ceph.conf"}],"name":"rook-config-override"}}]}},{"name":"rook-ceph-mons-keyring","secret":{"secretName":"rook-ceph-mons-keyring"}},{"hostPath":{"path":"/var/lib/rook/rook-ceph/log"},"name":"rook-ceph-log"},{"hostPath":{"path":"/var/lib/rook/rook-ceph/crash"},"name":"rook-ceph-crash"},{"hostPath":{"path":"/var/lib/rook/mon-c/data"},"name":"ceph-daemon-data"}]}}},"status":{}}'
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: "2021-09-22T09:04:52Z"
  generation: 157
  labels:
    app: rook-ceph-mon
    ceph-version: 16.2.6-0
    ceph_daemon_id: c
    ceph_daemon_type: mon
    mon: c
    mon_cluster: rook-ceph
    rook-version: v1.7.5
    rook_cluster: rook-ceph
  name: rook-ceph-mon-c
  namespace: rook-ceph
  ownerReferences:
  - apiVersion: ceph.rook.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: CephCluster
    name: rook-ceph
    uid: 6cef12f2-e7e1-4af1-a84b-202658a6dbf3
  resourceVersion: "50475566"
  uid: a7571389-03ab-4a35-aa90-98330f4ad624
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rook-ceph-mon
      ceph_daemon_id: c
      mon: c
      mon_cluster: rook-ceph
      rook_cluster: rook-ceph
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rook-ceph-mon
        ceph_daemon_id: c
        ceph_daemon_type: mon
        mon: c
        mon_cluster: rook-ceph
        rook_cluster: rook-ceph
      name: rook-ceph-mon-c
      namespace: rook-ceph
    spec:
      affinity: {}
      containers:
      - args:
        - --fsid=6023a4fd-488a-43e9-bc0b-d18d8a5609bb
        - --keyring=/etc/ceph/keyring-store/keyring
        - --log-to-stderr=true
        - --err-to-stderr=true
        - --mon-cluster-log-to-stderr=true
        - '--log-stderr-prefix=debug '
        - --default-log-to-file=false
        - --default-mon-cluster-log-to-file=false
        - --mon-host=$(ROOK_CEPH_MON_HOST)
        - --mon-initial-members=$(ROOK_CEPH_MON_INITIAL_MEMBERS)
        - --id=c
        - --setuser=ceph
        - --setgroup=ceph
        - --foreground
        - --public-addr=10.101.38.8
        - --setuser-match-path=/var/lib/ceph/mon/ceph-c/store.db
        - --public-bind-addr=$(ROOK_POD_IP)
        command:
        - ceph-mon
        env:
        - name: CONTAINER_IMAGE
          value: quay.io/ceph/ceph:v16.2.6
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_MEMORY_LIMIT
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: limits.memory
        - name: POD_MEMORY_REQUEST
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: requests.memory
        - name: POD_CPU_LIMIT
          valueFrom:
            resourceFieldRef:
              divisor: "1"
              resource: limits.cpu
        - name: POD_CPU_REQUEST
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: requests.cpu
        - name: ROOK_CEPH_MON_HOST
          valueFrom:
            secretKeyRef:
              key: mon_host
              name: rook-ceph-config
        - name: ROOK_CEPH_MON_INITIAL_MEMBERS
          valueFrom:
            secretKeyRef:
              key: mon_initial_members
              name: rook-ceph-config
        - name: ROOK_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: quay.io/ceph/ceph:v16.2.6
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - env
            - -i
            - sh
            - -c
            - ceph --admin-daemon /run/ceph/ceph-mon.c.asok mon_status
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: mon
        ports:
        - containerPort: 6789
          name: tcp-msgr1
          protocol: TCP
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/ceph
          name: rook-config-override
          readOnly: true
        - mountPath: /etc/ceph/keyring-store/
          name: rook-ceph-mons-keyring
          readOnly: true
        - mountPath: /var/log/ceph
          name: rook-ceph-log
        - mountPath: /var/lib/ceph/crash
          name: rook-ceph-crash
        - mountPath: /var/lib/ceph/mon/ceph-c
          name: ceph-daemon-data
        workingDir: /var/log/ceph
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - --verbose
        - --recursive
        - ceph:ceph
        - /var/log/ceph
        - /var/lib/ceph/crash
        - /var/lib/ceph/mon/ceph-c
        command:
        - chown
        image: quay.io/ceph/ceph:v16.2.6
        imagePullPolicy: IfNotPresent
        name: chown-container-data-dir
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/ceph
          name: rook-config-override
          readOnly: true
        - mountPath: /etc/ceph/keyring-store/
          name: rook-ceph-mons-keyring
          readOnly: true
        - mountPath: /var/log/ceph
          name: rook-ceph-log
        - mountPath: /var/lib/ceph/crash
          name: rook-ceph-crash
        - mountPath: /var/lib/ceph/mon/ceph-c
          name: ceph-daemon-data
      - args:
        - --fsid=6023a4fd-488a-43e9-bc0b-d18d8a5609bb
        - --keyring=/etc/ceph/keyring-store/keyring
        - --log-to-stderr=true
        - --err-to-stderr=true
        - --mon-cluster-log-to-stderr=true
        - '--log-stderr-prefix=debug '
        - --default-log-to-file=false
        - --default-mon-cluster-log-to-file=false
        - --mon-host=$(ROOK_CEPH_MON_HOST)
        - --mon-initial-members=$(ROOK_CEPH_MON_INITIAL_MEMBERS)
        - --id=c
        - --setuser=ceph
        - --setgroup=ceph
        - --public-addr=10.101.38.8
        - --mkfs
        command:
        - ceph-mon
        env:
        - name: CONTAINER_IMAGE
          value: quay.io/ceph/ceph:v16.2.6
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_MEMORY_LIMIT
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: limits.memory
        - name: POD_MEMORY_REQUEST
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: requests.memory
        - name: POD_CPU_LIMIT
          valueFrom:
            resourceFieldRef:
              divisor: "1"
              resource: limits.cpu
        - name: POD_CPU_REQUEST
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: requests.cpu
        - name: ROOK_CEPH_MON_HOST
          valueFrom:
            secretKeyRef:
              key: mon_host
              name: rook-ceph-config
        - name: ROOK_CEPH_MON_INITIAL_MEMBERS
          valueFrom:
            secretKeyRef:
              key: mon_initial_members
              name: rook-ceph-config
        image: quay.io/ceph/ceph:v16.2.6
        imagePullPolicy: IfNotPresent
        name: init-mon-fs
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/ceph
          name: rook-config-override
          readOnly: true
        - mountPath: /etc/ceph/keyring-store/
          name: rook-ceph-mons-keyring
          readOnly: true
        - mountPath: /var/log/ceph
          name: rook-ceph-log
        - mountPath: /var/lib/ceph/crash
          name: rook-ceph-crash
        - mountPath: /var/lib/ceph/mon/ceph-c
          name: ceph-daemon-data
      nodeSelector:
        kubernetes.io/hostname: ikp-p2p-worker1
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: rook-config-override
        projected:
          defaultMode: 420
          sources:
          - configMap:
              items:
              - key: config
                mode: 292
                path: ceph.conf
              name: rook-config-override
      - name: rook-ceph-mons-keyring
        secret:
          defaultMode: 420
          secretName: rook-ceph-mons-keyring
      - hostPath:
          path: /var/lib/rook/rook-ceph/log
          type: ""
        name: rook-ceph-log
      - hostPath:
          path: /var/lib/rook/rook-ceph/crash
          type: ""
        name: rook-ceph-crash
      - hostPath:
          path: /var/lib/rook/mon-c/data
          type: ""
        name: ceph-daemon-data
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-09-22T09:04:53Z"
    lastUpdateTime: "2022-01-06T02:43:53Z"
    message: ReplicaSet "rook-ceph-mon-c-6f869cbc9d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-01-06T03:43:19Z"
    lastUpdateTime: "2022-01-06T03:43:19Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 157
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
