apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "10"
  creationTimestamp: "2021-09-22T09:05:13Z"
  generation: 22
  labels:
    app: rook-ceph-crashcollector
    ceph-version: 16.2.6-0
    ceph_daemon_id: crash
    crashcollector: crash
    kubernetes.io/hostname: ikp-p2p-ceph3
    node_name: ikp-p2p-ceph3
    rook-version: v1.7.5
    rook_cluster: rook-ceph
  name: rook-ceph-crashcollector-ikp-p2p-ceph3
  namespace: rook-ceph
  ownerReferences:
  - apiVersion: ceph.rook.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: CephCluster
    name: rook-ceph
    uid: 6cef12f2-e7e1-4af1-a84b-202658a6dbf3
  resourceVersion: "42919929"
  uid: 2ecc8837-f005-41e6-8afb-01d20debf7e1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rook-ceph-crashcollector
      kubernetes.io/hostname: ikp-p2p-ceph3
      node_name: ikp-p2p-ceph3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rook-ceph-crashcollector
        ceph-version: 16.2.6-0
        ceph_daemon_id: crash
        crashcollector: crash
        kubernetes.io/hostname: ikp-p2p-ceph3
        node_name: ikp-p2p-ceph3
        rook-version: v1.7.5
        rook_cluster: rook-ceph
    spec:
      containers:
      - command:
        - ceph-crash
        env:
        - name: CONTAINER_IMAGE
          value: quay.io/ceph/ceph:v16.2.6
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_MEMORY_LIMIT
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: limits.memory
        - name: POD_MEMORY_REQUEST
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: requests.memory
        - name: POD_CPU_LIMIT
          valueFrom:
            resourceFieldRef:
              divisor: "1"
              resource: limits.cpu
        - name: POD_CPU_REQUEST
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: requests.cpu
        - name: ROOK_CEPH_MON_HOST
          valueFrom:
            secretKeyRef:
              key: mon_host
              name: rook-ceph-config
        - name: ROOK_CEPH_MON_INITIAL_MEMBERS
          valueFrom:
            secretKeyRef:
              key: mon_initial_members
              name: rook-ceph-config
        - name: CEPH_ARGS
          value: -m $(ROOK_CEPH_MON_HOST) -k /etc/ceph/crash-collector-keyring-store/keyring
        image: quay.io/ceph/ceph:v16.2.6
        imagePullPolicy: IfNotPresent
        name: ceph-crash
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/ceph
          name: rook-config-override
          readOnly: true
        - mountPath: /var/log/ceph
          name: rook-ceph-log
        - mountPath: /var/lib/ceph/crash
          name: rook-ceph-crash
        - mountPath: /etc/ceph/crash-collector-keyring-store/
          name: rook-ceph-crash-collector-keyring
          readOnly: true
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - /var/lib/ceph/crash/posted
        command:
        - mkdir
        - -p
        image: quay.io/ceph/ceph:v16.2.6
        imagePullPolicy: IfNotPresent
        name: make-container-crash-dir
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/ceph
          name: rook-config-override
          readOnly: true
        - mountPath: /var/log/ceph
          name: rook-ceph-log
        - mountPath: /var/lib/ceph/crash
          name: rook-ceph-crash
      - args:
        - --verbose
        - --recursive
        - ceph:ceph
        - /var/log/ceph
        - /var/lib/ceph/crash
        command:
        - chown
        image: quay.io/ceph/ceph:v16.2.6
        imagePullPolicy: IfNotPresent
        name: chown-container-data-dir
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/ceph
          name: rook-config-override
          readOnly: true
        - mountPath: /var/log/ceph
          name: rook-ceph-log
        - mountPath: /var/lib/ceph/crash
          name: rook-ceph-crash
      nodeSelector:
        kubernetes.io/hostname: ikp-p2p-ceph3
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 300
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 5
      volumes:
      - name: rook-config-override
        projected:
          defaultMode: 420
          sources:
          - configMap:
              items:
              - key: config
                mode: 292
                path: ceph.conf
              name: rook-config-override
      - hostPath:
          path: /var/lib/rook/rook-ceph/log
          type: ""
        name: rook-ceph-log
      - hostPath:
          path: /var/lib/rook/rook-ceph/crash
          type: ""
        name: rook-ceph-crash
      - name: rook-ceph-crash-collector-keyring
        secret:
          defaultMode: 420
          secretName: rook-ceph-crash-collector-keyring
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-01-06T03:43:13Z"
    lastUpdateTime: "2022-01-06T03:43:13Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-09-22T09:05:13Z"
    lastUpdateTime: "2022-01-06T03:51:36Z"
    message: ReplicaSet "rook-ceph-crashcollector-ikp-p2p-ceph3-7b4d7c9596" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 22
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
