version: '3.5'

services:
  app:
    build: .
    image: lenkunz/egat-p2p-trading-job:1.0.0-alpha.1
    environment:
      - BILATERAL_API_ENDPOINT=http://host.docker.internal:39083
      - FORECAST_API_ENDPOINT=http://host.docker.internal:39081
      - POWER_API_ENDPOINT=http://host.docker.internal:39082
      - POOL_API_ENDPOINT=http://host.docker.internal:39084
      - TRADE_API_ENDPOINT=http://host.docker.internal:39085

      - NODE_ENV=development

      - VAT_RATE=0.07

      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USER=root
      - MONGO_PASSWORD=example
      - MONGO_DATABASE=admin
    ports:
      - 39086:3000

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 19086:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo
