version: '3.5'

services:
  app:
    build: .
    image: lenkunz/egat-p2p-bilateral:1.0.0-beta
    restart: unless-stopped
    environment:
      - TRADE_API_ENDPOINT=http://host.docker.internal:39085
      - METER_API_ENDPOINT=https://egat-p2p-meter-api.di.iknowplus.co.th
      - NODE_ENV=development

      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USER=root
      - MONGO_PASSWORD=example
      - MONGO_DATABASE=admin
    ports:
      - 39083:3000

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 39183:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo
