apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: egat-p2p-web-admin-news-management-api
  name: egat-p2p-web-admin-news-management-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: egat-p2p-web-admin-news-management-api
  strategy: {}
  template:
    metadata:
      labels:
        app: egat-p2p-web-admin-news-management-api
    spec:
      nodeSelector:
        tier: api
      containers:
        - env:
            - name: HOST
              value: 0.0.0.0
            - name: KEYCLOAK_OPENID_BASE_URL
              value: http://keycloak/auth/realms/egat
            - name: MONGO_INITDB_DATABASENAME
              value: NewsDatabase
            - name: MONGO_INITDB_HOST
              value: news-mongodb-0-external
            - name: MONGO_INITDB_PASSWORD
              value: Passw0rdEGAT
            - name: MONGO_INITDB_PORT
              value: "27017"
            - name: MONGO_INITDB_USERNAME
              value: user
            - name: PORT
              value: "3007"
          image: phwuts/egat-p2p-web-admin-news-management-api:0.0.3
          name: egat-p2p-web-admin-news-management-api
          ports:
            - containerPort: 3007
          resources:
            request:
              memory: "64Mi"
            limits: 
              memory: "192Mi"
      restartPolicy: Always
status: {}
