---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: zookeeper-1-data
  name: zookeeper-1-data
  namespace: kafka-connect
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: zookeeper-2-data
  name: zookeeper-2-data
  namespace: kafka-connect
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: zookeeper-3-data
  name: zookeeper-3-data
  namespace: kafka-connect
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: zookeeper-1-txns
  name: zookeeper-1-txns
  namespace: kafka-connect
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: zookeeper-2-txns
  name: zookeeper-2-txns
  namespace: kafka-connect
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: zookeeper-3-txns
  name: zookeeper-3-txns
  namespace: kafka-connect
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: zookeeper-1-logs
  name: zookeeper-1-logs
  namespace: kafka-connect
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: zookeeper-2-logs
  name: zookeeper-2-logs
  namespace: kafka-connect
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: zookeeper-3-logs
  name: zookeeper-3-logs
  namespace: kafka-connect
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: zookeeper-1-conf
  name: zookeeper-1-conf
  namespace: kafka-connect
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: zookeeper-2-conf
  name: zookeeper-2-conf
  namespace: kafka-connect
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: zookeeper-3-conf
  name: zookeeper-3-conf
  namespace: kafka-connect
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: kafka-1-data
  name: kafka-1-data
  namespace: kafka-connect
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: kafka-2-data
  name: kafka-2-data
  namespace: kafka-connect
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: kafka-3-data
  name: kafka-3-data
  namespace: kafka-connect
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: kafka-1-logs
  name: kafka-1-logs
  namespace: kafka-connect
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: kafka-2-logs
  name: kafka-2-logs
  namespace: kafka-connect
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: kafka-3-logs
  name: kafka-3-logs
  namespace: kafka-connect
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: kafka-1-config
  name: kafka-1-config
  namespace: kafka-connect
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: kafka-2-config
  name: kafka-2-config
  namespace: kafka-connect
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: kafka-3-config
  name: kafka-3-config
  namespace: kafka-connect
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zookeeper-1
    component: zookeeper
  name: zookeeper-1
  namespace: kafka-connect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-1
      component: zookeeper
  strategy: {}
  template:
    metadata:
      labels:
        app: zookeeper-1
        component: zookeeper
    spec:
      nodeSelector:
        tier: broker
      containers:
      - image: debezium/zookeeper:1.2
        imagePullPolicy: IfNotPresent
        name: zookeeper-1
        command: 
        - /bin/sh
        args:
        - -c
        - rm -f $ZK_HOME/conf/zoo.cfg && /docker-entrypoint.sh start
        env:
        - name: SERVER_ID
          value: "1"
        - name: SERVER_COUNT
          value: "3"
        - name: LOG_LEVEL
          value: "INFO"
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
        resources:
          requests:
            memory: "2Gi"
          limits:
            memory: "4Gi"
        volumeMounts:
        - mountPath: /zookeeper/data
          name: zookeeper-1-data
        - mountPath: /zookeeper/txns
          name: zookeeper-1-txns
        - mountPath: /zookeeper/conf
          name: zookeeper-1-conf
      volumes:
      - name: zookeeper-1-data
        persistentVolumeClaim:
          claimName: zookeeper-1-data
      - name: zookeeper-1-txns
        persistentVolumeClaim:
          claimName: zookeeper-1-txns
      - name: zookeeper-1-conf
        persistentVolumeClaim:
          claimName: zookeeper-1-conf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zookeeper-2
    component: zookeeper
  name: zookeeper-2
  namespace: kafka-connect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-2
      component: zookeeper
  strategy: {}
  template:
    metadata:
      labels:
        app: zookeeper-2
        component: zookeeper
    spec:
      nodeSelector:
        tier: broker
      containers:
      - image: debezium/zookeeper:1.2
        imagePullPolicy: IfNotPresent
        name: zookeeper-2
        command: 
        - /bin/sh
        args:
        - -c
        - rm -f $ZK_HOME/conf/zoo.cfg && /docker-entrypoint.sh start
        env:
        - name: SERVER_ID
          value: "2"
        - name: SERVER_COUNT
          value: "3"
        - name: LOG_LEVEL
          value: "INFO"
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
        resources:
          requests:
            memory: "2Gi"
          limits:
            memory: "4Gi"
        volumeMounts:
        - mountPath: /zookeeper/data
          name: zookeeper-2-data
        - mountPath: /zookeeper/txns
          name: zookeeper-2-txns
        - mountPath: /zookeeper/conf
          name: zookeeper-2-conf
      volumes:
      - name: zookeeper-2-data
        persistentVolumeClaim:
          claimName: zookeeper-2-data
      - name: zookeeper-2-txns
        persistentVolumeClaim:
          claimName: zookeeper-2-txns
      - name: zookeeper-2-conf
        persistentVolumeClaim:
          claimName: zookeeper-2-conf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zookeeper-3
    component: zookeeper
  name: zookeeper-3
  namespace: kafka-connect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-3
      component: zookeeper
  strategy: {}
  template:
    metadata:
      labels:
        app: zookeeper-3
        component: zookeeper
    spec:
      nodeSelector:
        tier: broker
      containers:
      - image: debezium/zookeeper:1.2
        imagePullPolicy: IfNotPresent
        name: zookeeper-3
        command: 
        - /bin/sh
        args:
        - -c
        - rm -f $ZK_HOME/conf/zoo.cfg && /docker-entrypoint.sh start
        env:
        - name: SERVER_ID
          value: "3"
        - name: SERVER_COUNT
          value: "3"
        - name: LOG_LEVEL
          value: "INFO"
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
        resources:
          requests:
            memory: "2Gi"
          limits:
            memory: "4Gi"
        volumeMounts:
        - mountPath: /zookeeper/data
          name: zookeeper-3-data
        - mountPath: /zookeeper/txns
          name: zookeeper-3-txns
        - mountPath: /zookeeper/conf
          name: zookeeper-3-conf
      volumes:
      - name: zookeeper-3-data
        persistentVolumeClaim:
          claimName: zookeeper-3-data
      - name: zookeeper-3-txns
        persistentVolumeClaim:
          claimName: zookeeper-3-txns
      - name: zookeeper-3-conf
        persistentVolumeClaim:
          claimName: zookeeper-3-conf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-1
    component: kafka
  name: kafka-1
  namespace: kafka-connect
spec:
  replicas: 0
  selector:
    matchLabels:
      app: kafka-1
      component: kafka
  strategy: {}
  template:
    metadata:
      labels:
        app: kafka-1
        component: kafka
    spec:
      nodeSelector:
        tier: broker
      containers:
      - image: debezium/kafka:1.2
        imagePullPolicy: IfNotPresent
        name: kafka-1
        env:
        - name: BROKER_ID
          value: "1"
        - name: ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        - name: HOST_NAME
          value: "kafka-1-svc"
        - name: LISTENERS
          value: "PLAINTEXT://0.0.0.0:9092"
        - name: HEAP_OPTS
          value: "-Xms1G -Xmx4G"
        - name: LOG_LEVEL
          value: "INFO"
        - name: KAFKA_HOST_NAME
          value: "kafka-1"
        - name: KAFKA_PORT
          value: "9092"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://0.0.0.0:9092"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "kafka-1-svc"
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka-1-svc:9092"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: KAFKA_LOG_RETENTION_HOURS
          value: "1"
        - name: KAFKA_LOG_COMPRESSION_TYPE
          value: "gzip"
        ports:
        - containerPort: 9092
        resources:
          requests:
            memory: "2Gi"
          limits:
            memory: "4Gi"
        volumeMounts:
        - mountPath: /kafka/data
          name: kafka-1-data
        - mountPath: /kafka/logs
          name: kafka-1-logs
        - mountPath: /kafka/config
          name: kafka-1-config
      volumes:
      - name: kafka-1-data
        persistentVolumeClaim:
          claimName: kafka-1-data
      - name: kafka-1-logs
        persistentVolumeClaim:
          claimName: kafka-1-logs
      - name: kafka-1-config
        persistentVolumeClaim:
          claimName: kafka-1-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-2
    component: kafka
  name: kafka-2
  namespace: kafka-connect
spec:
  replicas: 0
  selector:
    matchLabels:
      app: kafka-2
      component: kafka
  strategy: {}
  template:
    metadata:
      labels:
        app: kafka-2
        component: kafka
    spec:
      nodeSelector:
        tier: broker
      containers:
      - image: debezium/kafka:1.2
        imagePullPolicy: IfNotPresent
        name: kafka-2
        env:
        - name: BROKER_ID
          value: "2"
        - name: ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        - name: HOST_NAME
          value: "kafka-2-svc"
        - name: LISTENERS
          value: "PLAINTEXT://0.0.0.0:9092"
        - name: HEAP_OPTS
          value: "-Xms1G -Xmx4G"
        - name: LOG_LEVEL
          value: "INFO"
        - name: KAFKA_HOST_NAME
          value: "kafka-2"
        - name: KAFKA_PORT
          value: "9092"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://0.0.0.0:9092"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "kafka-2-svc"
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka-2-svc:9092"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: KAFKA_LOG_RETENTION_HOURS
          value: "1"
        - name: KAFKA_LOG_COMPRESSION_TYPE
          value: "gzip"
        ports:
        - containerPort: 9092
        resources:
          requests:
            memory: "2Gi"
          limits:
            memory: "4Gi"
        volumeMounts:
        - mountPath: /kafka/data
          name: kafka-2-data
        - mountPath: /kafka/logs
          name: kafka-2-logs
        - mountPath: /kafka/config
          name: kafka-2-config
      volumes:
      - name: kafka-2-data
        persistentVolumeClaim:
          claimName: kafka-2-data
      - name: kafka-2-logs
        persistentVolumeClaim:
          claimName: kafka-2-logs
      - name: kafka-2-config
        persistentVolumeClaim:
          claimName: kafka-2-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-3
    component: kafka
  name: kafka-3
  namespace: kafka-connect
spec:
  replicas: 0
  selector:
    matchLabels:
      app: kafka-3
      component: kafka
  strategy: {}
  template:
    metadata:
      labels:
        app: kafka-3
        component: kafka
    spec:
      nodeSelector:
        tier: broker
      containers:
      - image: debezium/kafka:1.2
        imagePullPolicy: IfNotPresent
        name: kafka-3
        env:
        - name: BROKER_ID
          value: "3"
        - name: ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        - name: HOST_NAME
          value: "kafka-3-svc"
        - name: LISTENERS
          value: "PLAINTEXT://0.0.0.0:9092"
        - name: HEAP_OPTS
          value: "-Xms1G -Xmx4G"
        - name: LOG_LEVEL
          value: "INFO"
        - name: KAFKA_HOST_NAME
          value: "kafka-3"
        - name: KAFKA_PORT
          value: "9092"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://0.0.0.0:9092"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "kafka-3-svc"
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka-3-svc:9092"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: KAFKA_LOG_RETENTION_HOURS
          value: "1"
        - name: KAFKA_LOG_COMPRESSION_TYPE
          value: "gzip"
        ports:
        - containerPort: 9092
        resources:
          requests:
            memory: "2Gi"
          limits:
            memory: "4Gi"
        volumeMounts:
        - mountPath: /kafka/data
          name: kafka-3-data
        - mountPath: /kafka/logs
          name: kafka-3-logs
        - mountPath: /kafka/config
          name: kafka-3-config
      volumes:
      - name: kafka-3-data
        persistentVolumeClaim:
          claimName: kafka-3-data
      - name: kafka-3-logs
        persistentVolumeClaim:
          claimName: kafka-3-logs
      - name: kafka-3-config
        persistentVolumeClaim:
          claimName: kafka-3-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-1
  name: kafka-1-svc
  namespace: kafka-connect
spec:
  ports:
  - name: broker
    port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    app: kafka-1
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-2
  name: kafka-2-svc
  namespace: kafka-connect
spec:
  ports:
  - name: broker
    port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    app: kafka-2
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-3
  name: kafka-3-svc
  namespace: kafka-connect
spec:
  ports:
  - name: broker
    port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    app: kafka-3
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
  name: kafka
  namespace: kafka-connect
spec:
  ports:
  - name: broker
    port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    component: kafka
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper-1
  name: zookeeper-1
  namespace: kafka-connect
spec:
  ports:
  - name: server
    port: 2888
    protocol: TCP
    targetPort: 2888
  - name: leader-election
    port: 3888
    protocol: TCP
    targetPort: 3888
  selector:
    app: zookeeper-1
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper-2
  name: zookeeper-2
  namespace: kafka-connect
spec:
  ports:
  - name: server
    port: 2888
    protocol: TCP
    targetPort: 2888
  - name: leader-election
    port: 3888
    protocol: TCP
    targetPort: 3888
  selector:
    app: zookeeper-2
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper-3
  name: zookeeper-3
  namespace: kafka-connect
spec:
  ports:
  - name: server
    port: 2888
    protocol: TCP
    targetPort: 2888
  - name: leader-election
    port: 3888
    protocol: TCP
    targetPort: 3888
  selector:
    app: zookeeper-3
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: zookeeper
  name: zookeeper
  namespace: kafka-connect
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP
    targetPort: 2181
  selector:
    component: zookeeper
  type: ClusterIP
