---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: kafka-1-data
  name: kafka-1-data
  namespace: kafka-connect
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: kafka-2-data
  name: kafka-2-data
  namespace: kafka-connect
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: kafka-3-data
  name: kafka-3-data
  namespace: kafka-connect
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: kafka-1-logs
  name: kafka-1-logs
  namespace: kafka-connect
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: kafka-2-logs
  name: kafka-2-logs
  namespace: kafka-connect
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: kafka-3-logs
  name: kafka-3-logs
  namespace: kafka-connect
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: kafka-1-config
  name: kafka-1-config
  namespace: kafka-connect
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: kafka-2-config
  name: kafka-2-config
  namespace: kafka-connect
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: kafka-3-config
  name: kafka-3-config
  namespace: kafka-connect
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-1
    componet: kafka
  name: kafka-1
  namespace: kafka-connect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-1
      componet: kafka
  strategy: {}
  template:
    metadata:
      labels:
        app: kafka-1
        componet: kafka
    spec:
      nodeSelector:
        tier: broker
      containers:
      - image: debezium/kafka:latest
        imagePullPolicy: Always
        name: kafka-1
        env:
        - name: CLUSTER_ID
          value: "oh-sxaDRTcyAr6pFRbXyzA"
        - name: BROKER_ID
          value: "1"
        - name: NODE_ID
          value: "1"
        - name: NODE_ROLE
          value: "combined"
        - name: KAFKA_PROCESS_ROLES
          value: "broker,controller"
        - name: KAFKA_CONTROLLER_QUORUM_VOTERS
          value: "1@kafka-1-svc:9093,2@kafka-2-svc:9093,3@kafka-3-svc:9093"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "PLAINTEXT"
        - name: KAFKA_CONTROLLER_LISTENER_NAMES
          value: "CONTROLLER"
        - name: KAFKA_HEAP_OPTS
          value: "-Xmx4G -Xms1G"
        - name: LOG_LEVEL
          value: "INFO"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "kafka-1"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka-1-svc:29092,CONTROLLER://kafka-1-svc:9093,PLAINTEXT_HOST://kafka-1-svc:9092"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:9092"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: KAFKA_LOG_RETENTION_HOURS
          value: "2"
        - name: KAFKA_LOG_COMPRESSION_TYPE
          value: "gzip"
        - name: KAFKA_CLEANUP_POLICY
          value: "delete"
        - name: KAFKA_LOG_DELETE_RETENTION_MS
          value: "3600000"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "3"
        - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
          value: "0"
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "3"
        - name: KAFKA_LOG_DIRS
          value: "/kafka/logs"
        - name: KAFKA_REPLICA_SOCKET_TIMEOUT_MS
          value: "300000"
        ports:
        - containerPort: 29092
        - containerPort: 9092
        - containerPort: 9093
        resources:
          requests:
            memory: "2Gi"
          limits:
            memory: "4Gi"
        volumeMounts:
        - mountPath: /kafka/data
          name: kafka-1-data
        - mountPath: /kafka/logs
          name: kafka-1-logs
        - mountPath: /kafka/config
          name: kafka-1-config
      volumes:
      - name: kafka-1-data
        persistentVolumeClaim:
          claimName: kafka-1-data
      - name: kafka-1-logs
        persistentVolumeClaim:
          claimName: kafka-1-logs
      - name: kafka-1-config
        persistentVolumeClaim:
          claimName: kafka-1-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-2
    componet: kafka
  name: kafka-2
  namespace: kafka-connect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-2
      componet: kafka
  strategy: {}
  template:
    metadata:
      labels:
        app: kafka-2
        componet: kafka
    spec:
      nodeSelector:
        tier: broker
      containers:
      - image: debezium/kafka:latest
        imagePullPolicy: Always
        name: kafka-2
        env:
        - name: CLUSTER_ID
          value: "oh-sxaDRTcyAr6pFRbXyzA"
        - name: BROKER_ID
          value: "2"
        - name: NODE_ID
          value: "2"
        - name: NODE_ROLE
          value: "combined"
        - name: KAFKA_PROCESS_ROLES
          value: "broker,controller"
        - name: KAFKA_CONTROLLER_QUORUM_VOTERS
          value: "1@kafka-1-svc:9093,2@kafka-2-svc:9093,3@kafka-3-svc:9093"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "PLAINTEXT"
        - name: KAFKA_CONTROLLER_LISTENER_NAMES
          value: "CONTROLLER"
        - name: KAFKA_HEAP_OPTS
          value: "-Xmx4G -Xms1G"
        - name: LOG_LEVEL
          value: "INFO"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "kafka-2"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka-2-svc:29092,CONTROLLER://kafka-2-svc:9093,PLAINTEXT_HOST://kafka-2-svc:9092"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:9092"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: KAFKA_LOG_RETENTION_HOURS
          value: "2"
        - name: KAFKA_LOG_COMPRESSION_TYPE
          value: "gzip"
        - name: KAFKA_CLEANUP_POLICY
          value: "delete"
        - name: KAFKA_LOG_DELETE_RETENTION_MS
          value: "3600000"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "3"
        - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
          value: "0"
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "3"
        - name: KAFKA_LOG_DIRS
          value: "/kafka/logs"
        - name: KAFKA_REPLICA_SOCKET_TIMEOUT_MS
          value: "300000"
        ports:
        - containerPort: 29092
        - containerPort: 9092
        - containerPort: 9093
        resources:
          requests:
            memory: "2Gi"
          limits:
            memory: "4Gi"
        volumeMounts:
        - mountPath: /kafka/data
          name: kafka-2-data
        - mountPath: /kafka/logs
          name: kafka-2-logs
        - mountPath: /kafka/config
          name: kafka-2-config
      volumes:
      - name: kafka-2-data
        persistentVolumeClaim:
          claimName: kafka-2-data
      - name: kafka-2-logs
        persistentVolumeClaim:
          claimName: kafka-2-logs
      - name: kafka-2-config
        persistentVolumeClaim:
          claimName: kafka-2-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-3
    componet: kafka
  name: kafka-3
  namespace: kafka-connect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-3
      componet: kafka
  strategy: {}
  template:
    metadata:
      labels:
        app: kafka-3
        componet: kafka
    spec:
      nodeSelector:
        tier: broker
      containers:
      - image: debezium/kafka:latest
        imagePullPolicy: Always
        name: kafka-3
        env:
        - name: CLUSTER_ID
          value: "oh-sxaDRTcyAr6pFRbXyzA"
        - name: BROKER_ID
          value: "3"
        - name: NODE_ID
          value: "3"
        - name: NODE_ROLE
          value: "combined"
        - name: KAFKA_PROCESS_ROLES
          value: "broker,controller"
        - name: KAFKA_CONTROLLER_QUORUM_VOTERS
          value: "1@kafka-1-svc:9093,2@kafka-2-svc:9093,3@kafka-3-svc:9093"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "PLAINTEXT"
        - name: KAFKA_CONTROLLER_LISTENER_NAMES
          value: "CONTROLLER"
        - name: KAFKA_HEAP_OPTS
          value: "-Xmx4G -Xms1G"
        - name: LOG_LEVEL
          value: "INFO"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "kafka-3"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka-3-svc:29092,CONTROLLER://kafka-3-svc:9093,PLAINTEXT_HOST://kafka-3-svc:9092"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:9092"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: KAFKA_LOG_RETENTION_HOURS
          value: "2"
        - name: KAFKA_LOG_COMPRESSION_TYPE
          value: "gzip"
        - name: KAFKA_CLEANUP_POLICY
          value: "delete"
        - name: KAFKA_LOG_DELETE_RETENTION_MS
          value: "3600000"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "3"
        - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
          value: "0"
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "3"
        - name: KAFKA_LOG_DIRS
          value: "/kafka/logs"
        - name: KAFKA_REPLICA_SOCKET_TIMEOUT_MS
          value: "300000"
        ports:
        - containerPort: 29092
        - containerPort: 9092
        - containerPort: 9093
        resources:
          requests:
            memory: "2Gi"
          limits:
            memory: "4Gi"
        volumeMounts:
        - mountPath: /kafka/data
          name: kafka-3-data
        - mountPath: /kafka/logs
          name: kafka-3-logs
        - mountPath: /kafka/config
          name: kafka-3-config
      volumes:
      - name: kafka-3-data
        persistentVolumeClaim:
          claimName: kafka-3-data
      - name: kafka-3-logs
        persistentVolumeClaim:
          claimName: kafka-3-logs
      - name: kafka-3-config
        persistentVolumeClaim:
          claimName: kafka-3-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-1
  name: kafka-1-svc
  namespace: kafka-connect
spec:
  ports:
  - name: brokerplain
    port: 29092
    protocol: TCP
    targetPort: 29092
  - name: broker
    port: 9092
    protocol: TCP
    targetPort: 9092
  - name: quorum
    port: 9093
    protocol: TCP
    targetPort: 9093
  selector:
    app: kafka-1
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-2
  name: kafka-2-svc
  namespace: kafka-connect
spec:
  ports:
  - name: brokerplain
    port: 29092
    protocol: TCP
    targetPort: 29092
  - name: broker
    port: 9092
    protocol: TCP
    targetPort: 9092
  - name: quorum
    port: 9093
    protocol: TCP
    targetPort: 9093
  selector:
    app: kafka-2
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-3
  name: kafka-3-svc
  namespace: kafka-connect
spec:
  ports:
  - name: brokerplain
    port: 29092
    protocol: TCP
    targetPort: 29092
  - name: broker
    port: 9092
    protocol: TCP
    targetPort: 9092
  - name: quorum
    port: 9093
    protocol: TCP
    targetPort: 9093
  selector:
    app: kafka-3
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
  name: kafka
  namespace: kafka-connect
spec:
  ports:
  - name: broker
    port: 9092
    protocol: TCP
    targetPort: 9092
  - name: quorum
    port: 9093
    protocol: TCP
    targetPort: 9093
  selector:
    componet: kafka
  type: ClusterIP
