apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: rook-ceph.cephfs.csi.ceph.com
  creationTimestamp: "2022-01-08T03:52:33Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/component: kafka-broker
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/name: kafka
  name: datadir-kafka-0
  namespace: kafka-connect
  resourceVersion: "43658862"
  uid: 7f14494f-da29-42db-bdfe-114abe9769a0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
  volumeName: pvc-7f14494f-da29-42db-bdfe-114abe9769a0
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  phase: Bound
