apiVersion: v1
kind: Pod
metadata:
  name: kafka-client
  namespace: kafka
spec:
  nodeSelector:
    tier: broker
  containers:
  - name: kafka
    image: confluentinc/cp-kafka:5.0.1
    command:
      - sh
      - -c
      - "exec tail -f /dev/null"
    resources:
      request:
        memory: "64Mi"
      limits: 
        memory: "128Mi"

