apiVersion: v1
kind: Service
metadata:
  labels:
    apps: egat-p2p-mobile-profile-api
  name: egat-p2p-mobile-profile-api
spec:
  ports:
    - name: "3002"
      port: 3002
      targetPort: 3002
  selector:
    apps: egat-p2p-mobile-profile-api

