apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: egat-p2p-mobile-notification-api
  name: egat-p2p-mobile-notification-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: egat-p2p-mobile-notification-api
  strategy: {}
  template:
    metadata:
      labels:
        app: egat-p2p-mobile-notification-api
    spec:
      nodeSelector:
        tier: api
      containers:
        - env:
            - name: MONGO_DATABASE
              value: NotificationDatabase
            - name: MONGO_HOST
              value: notification-mongodb-headless
            - name: MONGO_PASSWORD
              value: Passw0rdEGAT
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USER
              value: user
            - name: NODE_ENV
              value: development
          image: lenkunz/egat-p2p-notification:1.6.0-beta
          name: egat-p2p-mobile-notification-api
          ports:
            - containerPort: 3000
            - containerPort: 9229
          resources:
            request:
              memory: "64Mi"
            limits: 
              memory: "192Mi"
      restartPolicy: Always
status: {}
