apiVersion: v1
kind: Service
metadata:
  labels:
    app: egat-p2p-web-admin-ref-management-api
  name: egat-p2p-web-admin-ref-management-api
spec:
  ports:
    - name: "3005"
      port: 3005
      targetPort: 3005
  selector:
    app: egat-p2p-web-admin-ref-management-api

