apiVersion: v1
kind: Service
metadata:
  labels:
    apps: egat-p2p-mobile-trading-job-api
  name: egat-p2p-mobile-trading-job-api
spec:
  ports:
    - name: "39086"
      port: 39086
      targetPort: 3000
  selector:
    apps: egat-p2p-mobile-trading-job-api
status:
  loadBalancer: {}
