apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    apps: egat-p2p-mobile-trading-job-api
  name: egat-p2p-mobile-trading-job-api
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: egat-p2p-mobile-trading-job-api
  strategy: {}
  template:
    metadata:
      labels:
        apps: egat-p2p-mobile-trading-job-api
    spec:
      containers:
        - env:
            - name: BILATERAL_API_ENDPOINT
              value: http://egat-p2p-mobile-bilateral-api
            - name: FORECAST_API_ENDPOINT
              value: http://egat-p2p-mobile-forecast-api
            - name: MONGO_DATABASE
              value: admin
            - name: MONGO_HOST
              value: mongo
            - name: MONGO_PASSWORD
              value: example
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USER
              value: root
            - name: NODE_ENV
              value: development
            - name: POOL_API_ENDPOINT
              value: http://egat-p2p-mobile-pool-api
            - name: POWER_API_ENDPOINT
              value: http://egat-p2p-mobile-power-api
            - name: TRADE_API_ENDPOINT
              value: http://egat-p2p-mobile-trade-api
            - name: VAT_RATE
              value: "0.07"
          image: lenkunz/egat-p2p-trading-job:1.0.0-alpha.1
          name: egat-p2p-mobile-trading-job-api
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
