apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --chart -f docker-compose.trading-job.yaml
    kompose.version: 1.25.0 (a70f80cc)
  creationTimestamp: null
  labels:
    apps: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --chart -f docker-compose.trading-job.yaml
        kompose.version: 1.25.0 (a70f80cc)
      creationTimestamp: null
      labels:
        apps: app
    spec:
      containers:
        - env:
            - name: BILATERAL_API_ENDPOINT
              value: http://host.docker.internal:39083
            - name: FORECAST_API_ENDPOINT
              value: http://host.docker.internal:39081
            - name: MONGO_DATABASE
              value: admin
            - name: MONGO_HOST
              value: mongo
            - name: MONGO_PASSWORD
              value: example
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USER
              value: root
            - name: NODE_ENV
              value: development
            - name: POOL_API_ENDPOINT
              value: http://host.docker.internal:39084
            - name: POWER_API_ENDPOINT
              value: http://host.docker.internal:39082
            - name: TRADE_API_ENDPOINT
              value: http://host.docker.internal:39085
            - name: VAT_RATE
              value: "0.07"
          image: lenkunz/egat-p2p-trading-job:1.0.0-alpha.1
          name: app
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
